function msg = plan_prep_message(pr, u)
%PLAN_PREP_MESSAGE  Plain-language popup text for the pre-test planner.
%   msg = PLAN_PREP_MESSAGE(pr, u) turns a plan_prep_numbers result `pr` into a
%   friendly message: how many parts to prepare and the first drop height, with
%   the brute-force contrast as reassurance. Pure. [compiled-app]
    if nargin < 2 || isempty(u), u = 'mm'; end
    msg = sprintf([ ...
        'Prepare %d parts.\n\n' ...
        'Start your first drop at %.2f %s (the middle of your guess).\n\n' ...
        'This targets %.4g%% reliability at %.4g%% confidence.\n' ...
        'A blind trial-and-error approach would need about %d parts for the same goal, ' ...
        'so the method saves you a lot of prints.'], ...
        pr.n_parts, pr.start_height, u, 100*pr.R, 100*pr.C, pr.n_bogey);
end
