function summary = summarize_spacer_batches(nominal_sizes_mm, readings_by_size)
%SUMMARIZE_SPACER_BATCHES Describe sampled spacers without tracking every piece.
% Each cell contains one row per sampled spacer and one column per reading.
% The typical thickness is the average of all readings for that size.

    if ~(isnumeric(nominal_sizes_mm) && isreal(nominal_sizes_mm) && ...
            isvector(nominal_sizes_mm) && ~isempty(nominal_sizes_mm) && ...
            all(isfinite(nominal_sizes_mm)) && all(nominal_sizes_mm > 0) && ...
            iscell(readings_by_size) && ...
            numel(readings_by_size) == numel(nominal_sizes_mm))
        error('summarize_spacer_batches:badInput', ...
            'Provide one positive spacer label and one reading table for each size.');
    end

    empty_summary = struct( ...
        'nominal_size_mm',NaN, ...
        'sampled_spacer_count',0, ...
        'readings_per_spacer',0, ...
        'typical_thickness_mm',NaN, ...
        'lowest_spacer_average_mm',NaN, ...
        'highest_spacer_average_mm',NaN, ...
        'lowest_reading_mm',NaN, ...
        'highest_reading_mm',NaN);
    summary = repmat(empty_summary,1,numel(nominal_sizes_mm));

    for size_number = 1:numel(nominal_sizes_mm)
        readings = readings_by_size{size_number};
        if ~(isnumeric(readings) && isreal(readings) && ismatrix(readings) && ...
                ~isempty(readings) && all(isfinite(readings(:))) && ...
                all(readings(:) >= 0))
            error('summarize_spacer_batches:badReadings', ...
                'Every sampled spacer needs the same number of finite, nonnegative readings.');
        end
        spacer_averages = mean(readings,2);
        summary(size_number) = struct( ...
            'nominal_size_mm',double(nominal_sizes_mm(size_number)), ...
            'sampled_spacer_count',size(readings,1), ...
            'readings_per_spacer',size(readings,2), ...
            'typical_thickness_mm',mean(readings(:)), ...
            'lowest_spacer_average_mm',min(spacer_averages), ...
            'highest_spacer_average_mm',max(spacer_averages), ...
            'lowest_reading_mm',min(readings(:)), ...
            'highest_reading_mm',max(readings(:)));
    end
end
