function plan = estimate_study_plan(clean, reachable_model)
%ESTIMATE_STUDY_PLAN Produce a transparent requirements-first preparation plan.
% This is a pre-test estimate. It is not a final reliability claim and its
% rule version must be checked against the recorded simulation evidence.

    if ~isstruct(clean) || ~all(isfield(clean, {'mode', 'outcome', ...
            'reliability', 'confidence', 'accuracy_mm', ...
            'interaction_gap_mm', 'no_interaction_gap_mm', ...
            'minimum_gap_mm', 'maximum_gap_mm', ...
            'previous_information'}))
        error('estimate_study_plan:badInput', ...
            'Validated pre-test planner answers are required.');
    end
    if ~strcmp(clean.mode, 'requirements_first')
        error('estimate_study_plan:badMode', ...
            'This calculation needs the requirements-first planner mode.');
    end
    if ~isstruct(reachable_model) || ~isfield(reachable_model, 'gaps_mm')
        error('estimate_study_plan:badReachableModel', ...
            'The reachable physical gaps must be prepared before calculating the plan.');
    end

    z95 = shape_model(0.95, 'quantile');
    midpoint_mm = 0.5 * (clean.interaction_gap_mm + ...
        clean.no_interaction_gap_mm);
    expected_sigma_mm = (clean.no_interaction_gap_mm - ...
        clean.interaction_gap_mm) / (2 * z95);
    expected_sigma_mm = adjust_previous_information(expected_sigma_mm, clean);

    settings = neyer_settings();
    main_result = plan_samples(legacy_tail(clean.outcome), ...
        clean.reliability, clean.confidence, settings, ...
        struct('sigma', expected_sigma_mm, ...
        'accuracy_mm', clean.accuracy_mm));
    moderate_result = plan_samples(legacy_tail(clean.outcome), ...
        clean.reliability, clean.confidence, settings, ...
        struct('sigma', 1.5 * expected_sigma_mm, ...
        'accuracy_mm', clean.accuracy_mm));
    difficult_result = plan_samples(legacy_tail(clean.outcome), ...
        clean.reliability, clean.confidence, settings, ...
        struct('sigma', 2.0 * expected_sigma_mm, ...
        'accuracy_mm', clean.accuracy_mm));

    main_articles = main_result.n_recommended;
    reserve_1_articles = max(0, moderate_result.n_recommended - main_articles);
    reserve_2_articles = max(0, difficult_result.n_recommended - ...
        moderate_result.n_recommended);
    total_articles = main_articles + reserve_1_articles + reserve_2_articles;

    [~, start_row] = min(abs(reachable_model.gaps_mm - midpoint_mm));
    starting_gap_mm = reachable_model.gaps_mm(start_row);

    reliability_k = shape_model(clean.reliability, 'quantile');
    if strcmp(clean.outcome, 'interaction')
        estimated_target_gap_mm = midpoint_mm - reliability_k * expected_sigma_mm;
    else
        estimated_target_gap_mm = midpoint_mm + reliability_k * expected_sigma_mm;
    end
    [reachable_target_gap_mm, reachable_status] = round_reachable_gap( ...
        estimated_target_gap_mm, clean.outcome, reachable_model, []);

    assumptions = strings(0, 1);
    if strcmp(clean.previous_information, 'first_study')
        assumptions(end + 1, 1) = [ ...
            "This is treated as a first study with no fitted earlier result."];
        assumptions(end + 1, 1) = [ ...
            "Each almost-every-time endpoint is treated as 95%, not 100%."];
    end
    assumptions(end + 1, 1) = sprintf([ ...
        'The starting overall variation is estimated as %.4g mm from the two endpoint answers.'], ...
        expected_sigma_mm);
    assumptions(end + 1, 1) = [ ...
        "Reserve group 1 checks 1.5 times the starting variation; " + ...
        "reserve group 2 extends that check to 2 times the starting variation."];
    assumptions(end + 1, 1) = [ ...
        "Those reserve sizes are recommendations until the recorded virtual study is accepted."];

    suggestions = strings(0, 1);
    feasible = true;
    plan_kind = 'full_study';

    uncertainty_ratio = expected_sigma_mm / clean.accuracy_mm;
    if strcmp(clean.previous_information, 'first_study') && uncertainty_ratio > 50
        feasible = false;
        plan_kind = 'discovery';
        suggestions(end + 1, 1) = [ ...
            "Begin with a smaller discovery study. The first-study range is too broad " + ...
            "for one trustworthy full-study quantity at the requested accuracy."];
    end

    if strcmp(reachable_status.code, 'ok')
        physical_rounding_error_mm = abs(reachable_target_gap_mm - ...
            estimated_target_gap_mm);
    else
        physical_rounding_error_mm = Inf;
    end
    if physical_rounding_error_mm > clean.accuracy_mm
        feasible = false;
        suggestions(end + 1, 1) = [ ...
            "Improve the physical gap capability or accept wider gap accuracy; " + ...
            "the current reachable settings cannot meet the requested accuracy safely."];
    end
    if estimated_target_gap_mm < clean.minimum_gap_mm || ...
            estimated_target_gap_mm > clean.maximum_gap_mm
        feasible = false;
        suggestions(end + 1, 1) = [ ...
            "The estimated reliability gap is outside the permitted range. " + ...
            "Widen the permitted range only if the equipment and safety rules allow it."];
    end
    if isempty(suggestions)
        suggestions = [ ...
            "No change is suggested before recorded virtual validation."];
    end

    plan = struct( ...
        'schema_version', '1.0', ...
        'rule_version', 'absolute-gap-n-minus-15-provisional-1', ...
        'mode', clean.mode, ...
        'outcome', clean.outcome, ...
        'reliability', clean.reliability, ...
        'confidence', clean.confidence, ...
        'accuracy_mm', clean.accuracy_mm, ...
        'interaction_gap_mm', clean.interaction_gap_mm, ...
        'no_interaction_gap_mm', clean.no_interaction_gap_mm, ...
        'minimum_gap_mm', clean.minimum_gap_mm, ...
        'maximum_gap_mm', clean.maximum_gap_mm, ...
        'physical_setup', clean.physical_setup, ...
        'reachable_model', reachable_model, ...
        'main_articles', main_articles, ...
        'reserve_1_articles', reserve_1_articles, ...
        'reserve_2_articles', reserve_2_articles, ...
        'total_articles', total_articles, ...
        'starting_gap_mm', starting_gap_mm, ...
        'estimated_middle_gap_mm', midpoint_mm, ...
        'estimated_sigma_mm', expected_sigma_mm, ...
        'estimated_target_gap_mm', estimated_target_gap_mm, ...
        'reachable_target_gap_mm', reachable_target_gap_mm, ...
        'physical_rounding_error_mm', physical_rounding_error_mm, ...
        'reachable_status', reachable_status, ...
        'checkpoint_status', 'not_started', ...
        'plan_kind', plan_kind, ...
        'feasible', feasible, ...
        'assumptions', assumptions, ...
        'suggestions', suggestions, ...
        'validation_basis', [ ...
            'Published large-sample Neyer variance starting estimate with the ' ...
            'N-15 spread correction; final quantities require recorded virtual validation.']);
end

function name = legacy_tail(outcome)
    if strcmp(outcome, 'interaction')
        name = 'break';
    else
        name = 'survive';
    end
end

function sigma_mm = adjust_previous_information(sigma_mm, clean)
    switch clean.previous_information
        case 'sudden'
            sigma_mm = 0.5 * sigma_mm;
        case 'gradual'
            sigma_mm = 2.0 * sigma_mm;
        case 'advanced_value'
            if ~isfield(clean, 'previous_sigma_mm') || ...
                    ~(isscalar(clean.previous_sigma_mm) && ...
                    isfinite(clean.previous_sigma_mm) && clean.previous_sigma_mm > 0)
                error('estimate_study_plan:missingPreviousSigma', ...
                    'Enter the positive previous overall-variation value in millimetres.');
            end
            sigma_mm = clean.previous_sigma_mm;
    end
end
