function msg = plan_prep_message(pr, u)
%PLAN_PREP_MESSAGE  Plain-language popup text for the pre-test planner.
%   msg = PLAN_PREP_MESSAGE(pr, u) turns a plan_prep_numbers result `pr` into a
%   friendly message: how many test specimens to prepare and the first gap, with
%   the brute-force contrast as reassurance. Pure. [compiled-app]
    if nargin < 2 || isempty(u), u = 'mm'; end
    if isfield(pr, 'main_articles')
        if isfield(pr, 'reliability_instruction_supported') && ...
                ~pr.reliability_instruction_supported
            if strcmp(pr.reliability_instruction_status, ...
                    'exploratory_confidence')
                reliability_note = [ ...
                    'Reliability instruction: exploratory only\n' ...
                    'At 50%% confidence or less, the app will not issue a ' ...
                    'safety-supported operating setting.\n'];
            else
                reliability_note = [ ...
                    'Reliability instruction: outside recorded validation\n' ...
                    'Above 95%% confidence, the app will calculate an estimate ' ...
                    'but will not issue a safety-supported operating setting.\n'];
            end
        else
            reliability_note = sprintf([ ...
                'Reliability safety rule: %d independent articles\n' ...
                'The smaller main study may estimate the middle gap and overall variation.\n' ...
                'A supported reliability result is withheld until this safety total is reached.\n'], ...
                pr.reliability_validation_floor_articles);
        end
        msg = sprintf([ ...
            'Pre-test estimate\n\n' ...
            'Main study: %d articles\n' ...
            'This is the quantity expected for the starting assumptions.\n\n' ...
            'Reserve group 1: %d articles\n' ...
            'Use only after the main-study checkpoint asks for them.\n\n' ...
            'Reserve group 2: %d articles\n' ...
            'Use only after the next declared checkpoint asks for them.\n\n' ...
            'Total to prepare: %d articles\n\n' ...
            '%s' ...
            'Reserve articles are not used automatically. You decide at each checkpoint.\n\n' ...
            'First requested gap: %.2f %s\n' ...
            'This is the closest reachable gap to the starting middle estimate.\n\n' ...
            'Important: this is a planning estimate, not a reliability guarantee.'], ...
            pr.main_articles, pr.reserve_1_articles, pr.reserve_2_articles, ...
            pr.total_articles, reliability_note, pr.starting_gap_mm, u);
        return;
    end
    msg = sprintf([ ...
        'Prepare %d test specimens.\n\n' ...
        'Build the first gap at %.2f %s (the middle of your guess).\n\n' ...
        'This targets %.4g%% reliability at %.4g%% confidence.\n' ...
        'A direct counting approach would need about %d specimens for the same goal, ' ...
        'so the method uses the available tests efficiently.'], ...
        pr.n_parts, pr.start_height, u, 100*pr.R, 100*pr.C, pr.n_bogey);
end
