function msg = plan_prep_message(pr, u)
%PLAN_PREP_MESSAGE  Plain-language popup text for the pre-test planner.
%   msg = PLAN_PREP_MESSAGE(pr, u) turns a plan_prep_numbers result `pr` into a
%   friendly message: how many test specimens to prepare and the first gap, with
%   the brute-force contrast as reassurance. Pure. [compiled-app]
    if nargin < 2 || isempty(u), u = 'mm'; end
    msg = sprintf([ ...
        'Prepare %d test specimens.\n\n' ...
        'Build the first gap at %.2f %s (the middle of your guess).\n\n' ...
        'This targets %.4g%% reliability at %.4g%% confidence.\n' ...
        'A direct counting approach would need about %d specimens for the same goal, ' ...
        'so the method uses the available tests efficiently.'], ...
        pr.n_parts, pr.start_height, u, 100*pr.R, 100*pr.C, pr.n_bogey);
end
