function selected_plan = pretest_planner_ui()
%PRETEST_PLANNER_UI Guided preparation worksheet for a Neyer gap study.
% Calculations live in tested pure functions. This window only collects
% answers, explains their meaning, and presents the review.

    if ~(isdeployed || usejava('desktop'))
        error('pretest_planner_ui:noDisplay', ...
            'The Pre-Test Planner needs the MATLAB desktop.');
    end

    color.graphite = [33 49 58] / 255;
    color.blue = [35 108 142] / 255;
    color.teal = [47 125 109] / 255;
    color.amber = [181 117 25] / 255;
    color.rust = [164 61 53] / 255;
    color.white = [247 249 250] / 255;
    color.soft = [232 238 241] / 255;

    state.current_plan = [];
    state.selected_plan = [];

    figure_handle = uifigure('Name', 'Neyer Pre-Test Planner', ...
        'Position', [90 45 1180 790], 'Color', color.white);
    page = uigridlayout(figure_handle, [4 2]);
    page.RowHeight = {38, 58, '1x', 58};
    page.ColumnWidth = {620, '1x'};
    page.Padding = [26 20 26 20];
    page.RowSpacing = 12;
    page.ColumnSpacing = 22;

    progress = uilabel(page, 'Text', ...
        'Plan  >  Prepare  >  Test  >  Check  >  Finish', ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'FontColor', color.blue, 'HorizontalAlignment', 'left');
    progress.Layout.Row = 1;
    progress.Layout.Column = [1 2];

    title_label = uilabel(page, 'Text', ...
        'Plan the articles and gaps before the laboratory', ...
        'FontSize', 20, 'FontWeight', 'bold', 'FontColor', color.graphite);
    title_label.Layout.Row = 2;
    title_label.Layout.Column = [1 2];

    input_panel = uipanel(page, 'Title', 'Your planning answers', ...
        'FontSize', 16, 'FontWeight', 'bold', 'ForegroundColor', color.graphite, ...
        'BackgroundColor', color.white, 'Scrollable', 'on');
    input_panel.Layout.Row = 3;
    input_panel.Layout.Column = 1;
    inputs = uigridlayout(input_panel, [38 2]);
    inputs.RowHeight = repmat({'fit'}, 1, 38);
    inputs.ColumnWidth = {'1x', 220};
    inputs.Padding = [18 14 18 18];
    inputs.RowSpacing = 7;
    inputs.ColumnSpacing = 14;

    row = 1;
    add_section('How would you like to plan?');
    mode = add_dropdown('Planning question', ...
        {'Requirements first', 'Articles available first'}, ...
        {'requirements_first', 'available_articles_first'}, ...
        'Choose requirements first to calculate a preparation quantity.');
    mode.ValueChangedFcn = @(~, ~) update_mode_visibility();

    [available_count, available_label, available_help, ...
        available_question_row, available_help_row] = add_number( ...
        'Maximum articles available', 100, ...
        'How many separate destructive articles can be prepared.');
    [fixed_choice, fixed_label, fixed_help, ...
        fixed_question_row, fixed_help_row] = add_dropdown( ...
        'Keep this requirement fixed', ...
        {'Reliability', 'Confidence'}, {'reliability', 'confidence'}, ...
        'The planner estimates the other value; it never invents both.');

    add_section('What result do you need?');
    outcome = add_dropdown('Required physical result', ...
        {'Choose...', 'Interaction', 'No interaction'}, ...
        {'', 'interaction', 'no_interaction'}, ...
        'The physical result you need the final operating gap to produce.');
    reliability = add_number('Reliability (%)', 99, ...
        'The minimum fraction of similar articles expected to give that result.');
    confidence = add_number('Confidence (%)', 95, ...
        'How strongly the completed evidence must support the reliability.');
    accuracy = add_number('Required gap accuracy (+/- mm)', 0.10, ...
        'How close the calculated gap needs to be in millimetres.');

    add_section('What do you know?');
    interaction_gap = add_number('Almost-always Interaction gap (mm)', 1.00, ...
        'A smaller gap where Interaction is expected almost every time.');
    no_interaction_gap = add_number('Almost-always No-interaction gap (mm)', 10.00, ...
        'A larger gap where No interaction is expected almost every time.');
    previous_information = add_dropdown('Earlier information', ...
        {'No, this is my first study', 'Results change suddenly', ...
         'Results change gradually'}, ...
        {'first_study', 'sudden', 'gradual'}, ...
        'First-study endpoints are treated as at least 95%, not as certainty.');

    add_section('What can you build?');
    minimum_gap = add_number('Minimum permitted gap (mm)', 0.00, ...
        'The smallest permitted physical gap, including no spacers.');
    maximum_gap = add_number('Maximum permitted gap (mm)', 10.00, ...
        'The largest useful gap; larger obvious No-interaction gaps add no value.');
    physical_mode = add_dropdown('Physical setup method', ...
        {'Regular increments', 'Spacer and foil combinations', ...
         'Confirmed reachable-gap list'}, ...
        {'regular', 'combinations', 'list'}, ...
        'Use combinations when printed spacers make whole millimetres and foil adds decimals.');
    physical_mode.ValueChangedFcn = @(~, ~) update_physical_visibility();
    [regular_increment, regular_label, regular_help, ...
        regular_question_row, regular_help_row] = add_number( ...
        'Regular increment (mm)', 0.10, ...
        'Use this only when every multiple can genuinely be built.');
    [confirmed_list, list_label, list_help, ...
        list_question_row, list_help_row] = add_text( ...
        'Confirmed gaps (mm)', '0, 0.5, 1, 2, 10', ...
        'Enter only measured buildable gaps, separated by commas.');

    component_label = uilabel(inputs, 'Text', ...
        'Measured components and maximum count', 'FontSize', 14, ...
        'FontWeight', 'bold', 'FontColor', color.graphite);
    component_label.Layout.Row = row;
    component_label.Layout.Column = [1 2];
    component_label_row = row;
    row = row + 1;
    component_table = uitable(inputs, 'ColumnName', ...
        {'Component', 'Measured mm', 'Maximum count'}, ...
        'ColumnEditable', [true true true], ...
        'ColumnFormat', {'char', 'numeric', 'numeric'}, ...
        'Data', {'Foil layer', NaN, 0; 'Printed spacer 1', NaN, 0; ...
                 'Printed spacer 2', NaN, 0; 'Printed spacer 3', NaN, 0}, ...
        'RowName', [], 'FontSize', 12);
    component_table.Layout.Row = row;
    component_table.Layout.Column = [1 2];
    inputs.RowHeight{row} = 116;
    component_table_row = row;

    review_panel = uipanel(page, 'Title', 'Plan review', ...
        'FontSize', 16, 'FontWeight', 'bold', 'ForegroundColor', color.graphite, ...
        'BackgroundColor', [1 1 1]);
    review_panel.Layout.Row = 3;
    review_panel.Layout.Column = 2;
    review_grid = uigridlayout(review_panel, [3 1]);
    review_grid.RowHeight = {42, '1x', 34};
    review_grid.Padding = [18 14 18 16];
    review_heading = uilabel(review_grid, 'Text', ...
        'Complete the questions, then select Review plan.', ...
        'FontSize', 14, 'FontWeight', 'bold', 'FontColor', color.blue, ...
        'WordWrap', 'on');
    review_text = uitextarea(review_grid, 'Editable', 'off', ...
        'FontSize', 13, 'Value', { ...
        'Nothing has been calculated yet.', ...
        '', ...
        'Every quantity will be shown as an estimate with its assumptions.'});
    review_status = uilabel(review_grid, 'Text', 'Not reviewed', ...
        'FontSize', 12, 'FontColor', color.amber);

    buttons = uigridlayout(page, [1 4]);
    buttons.Layout.Row = 4;
    buttons.Layout.Column = [1 2];
    buttons.ColumnWidth = {'1x', '1x', 180, 130};
    buttons.Padding = [0 5 0 0];
    buttons.ColumnSpacing = 12;
    review_button = uibutton(buttons, 'Text', 'Review plan', ...
        'FontSize', 16, 'FontWeight', 'bold', ...
        'BackgroundColor', color.blue, 'FontColor', [1 1 1], ...
        'ButtonPushedFcn', @(~, ~) review_plan());
    save_button = uibutton(buttons, 'Text', 'Save plan', ...
        'FontSize', 16, 'FontWeight', 'bold', ...
        'BackgroundColor', color.teal, 'FontColor', [1 1 1], ...
        'Enable', 'off', 'ButtonPushedFcn', @(~, ~) save_plan());
    uilabel(buttons, 'Text', '');
    uibutton(buttons, 'Text', 'Close', 'FontSize', 15, ...
        'ButtonPushedFcn', @(~, ~) close_planner());

    figure_handle.CloseRequestFcn = @(~, ~) close_planner();
    update_mode_visibility();
    update_physical_visibility();
    uiwait(figure_handle);
    selected_plan = state.selected_plan;
    if isvalid(figure_handle), delete(figure_handle); end

    function add_section(text_value)
        label = uilabel(inputs, 'Text', text_value, 'FontSize', 16, ...
            'FontWeight', 'bold', 'FontColor', color.blue);
        label.Layout.Row = row;
        label.Layout.Column = [1 2];
        row = row + 1;
    end

    function [control, question_label, help_label, question_row, help_row] = add_number( ...
            question, default_value, help_text)
        question_row = row;
        question_label = uilabel(inputs, 'Text', question, 'FontSize', 14, ...
            'FontWeight', 'bold', 'FontColor', color.graphite, 'WordWrap', 'on');
        question_label.Layout.Row = row;
        question_label.Layout.Column = 1;
        control = uieditfield(inputs, 'numeric', 'Value', default_value, ...
            'FontSize', 14);
        control.Layout.Row = row;
        control.Layout.Column = 2;
        row = row + 1;
        help_row = row;
        help_label = uilabel(inputs, 'Text', help_text, 'FontSize', 12, ...
            'FontColor', [0.32 0.39 0.43], 'WordWrap', 'on');
        help_label.Layout.Row = row;
        help_label.Layout.Column = [1 2];
        row = row + 1;
    end

    function [control, question_label, help_label, question_row, help_row] = add_text( ...
            question, default_value, help_text)
        question_row = row;
        question_label = uilabel(inputs, 'Text', question, 'FontSize', 14, ...
            'FontWeight', 'bold', 'FontColor', color.graphite, 'WordWrap', 'on');
        question_label.Layout.Row = row;
        question_label.Layout.Column = 1;
        control = uieditfield(inputs, 'text', 'Value', default_value, ...
            'FontSize', 14);
        control.Layout.Row = row;
        control.Layout.Column = 2;
        row = row + 1;
        help_row = row;
        help_label = uilabel(inputs, 'Text', help_text, 'FontSize', 12, ...
            'FontColor', [0.32 0.39 0.43], 'WordWrap', 'on');
        help_label.Layout.Row = row;
        help_label.Layout.Column = [1 2];
        row = row + 1;
    end

    function [control, question_label, help_label, question_row, help_row] = add_dropdown( ...
            question, item_names, item_data, help_text)
        question_row = row;
        question_label = uilabel(inputs, 'Text', question, 'FontSize', 14, ...
            'FontWeight', 'bold', 'FontColor', color.graphite, 'WordWrap', 'on');
        question_label.Layout.Row = row;
        question_label.Layout.Column = 1;
        control = uidropdown(inputs, 'Items', item_names, ...
            'ItemsData', item_data, 'FontSize', 14);
        control.Layout.Row = row;
        control.Layout.Column = 2;
        row = row + 1;
        help_row = row;
        help_label = uilabel(inputs, 'Text', help_text, 'FontSize', 12, ...
            'FontColor', [0.32 0.39 0.43], 'WordWrap', 'on');
        help_label.Layout.Row = row;
        help_label.Layout.Column = [1 2];
        row = row + 1;
    end

    function update_mode_visibility()
        show_available = strcmp(mode.Value, 'available_articles_first');
        available_count.Visible = matlab.lang.OnOffSwitchState(show_available);
        available_label.Visible = matlab.lang.OnOffSwitchState(show_available);
        available_help.Visible = matlab.lang.OnOffSwitchState(show_available);
        fixed_choice.Visible = matlab.lang.OnOffSwitchState(show_available);
        fixed_label.Visible = matlab.lang.OnOffSwitchState(show_available);
        fixed_help.Visible = matlab.lang.OnOffSwitchState(show_available);
    end

    function update_physical_visibility()
        regular_increment.Visible = matlab.lang.OnOffSwitchState( ...
            strcmp(physical_mode.Value, 'regular'));
        regular_label.Visible = regular_increment.Visible;
        regular_help.Visible = regular_increment.Visible;
        confirmed_list.Visible = matlab.lang.OnOffSwitchState( ...
            strcmp(physical_mode.Value, 'list'));
        list_label.Visible = confirmed_list.Visible;
        list_help.Visible = confirmed_list.Visible;
        show_components = strcmp(physical_mode.Value, 'combinations');
        component_label.Visible = matlab.lang.OnOffSwitchState(show_components);
        component_table.Visible = matlab.lang.OnOffSwitchState(show_components);
    end

    function review_plan()
        try
            physical_setup = collect_physical_setup();
            raw = struct('mode', mode.Value, 'outcome', outcome.Value, ...
                'reliability', reliability.Value, 'confidence', confidence.Value, ...
                'accuracy_mm', accuracy.Value, ...
                'interaction_gap_mm', interaction_gap.Value, ...
                'no_interaction_gap_mm', no_interaction_gap.Value, ...
                'minimum_gap_mm', minimum_gap.Value, ...
                'maximum_gap_mm', maximum_gap.Value, ...
                'previous_information', previous_information.Value, ...
                'available_articles', available_count.Value, ...
                'physical_setup', physical_setup);
            [clean, input_messages] = validate_plan_inputs(raw);
            reachable = reachable_gap_model(physical_setup, ...
                clean.minimum_gap_mm, clean.maximum_gap_mm);

            if strcmp(clean.mode, 'requirements_first')
                plan = estimate_study_plan(clean, reachable);
                state.current_plan = plan;
                lines = plan_review_lines(plan, input_messages);
            else
                estimate = estimate_supported_targets(clean, reachable, ...
                    fixed_choice.Value);
                [plan, lines] = available_review(clean, reachable, estimate, ...
                    input_messages);
                state.current_plan = plan;
            end
            review_text.Value = cellstr(lines);
            if isempty(state.current_plan)
                save_button.Enable = 'off';
                review_status.Text = 'No saveable plan yet';
                review_status.FontColor = color.amber;
            elseif state.current_plan.feasible
                save_button.Enable = 'on';
                review_status.Text = 'Planning estimate ready for review';
                review_status.FontColor = color.teal;
            else
                save_button.Enable = 'on';
                review_status.Text = 'Review the cautions before saving';
                review_status.FontColor = color.amber;
            end
            review_heading.Text = 'What the current answers mean';
        catch calculation_error
            state.current_plan = [];
            save_button.Enable = 'off';
            review_status.Text = 'Please correct the highlighted planning issue';
            review_status.FontColor = color.rust;
            uialert(figure_handle, calculation_error.message, ...
                'Please check this answer', 'Icon', 'warning');
        end
    end

    function setup = collect_physical_setup()
        switch physical_mode.Value
            case 'regular'
                setup = struct('mode', 'regular', ...
                    'increment_mm', regular_increment.Value);
            case 'list'
                pieces = regexp(strtrim(confirmed_list.Value), ...
                    '[,;\s]+', 'split');
                pieces = pieces(~cellfun('isempty', pieces));
                gaps = cellfun(@str2double, pieces);
                setup = struct('mode', 'list', 'gaps_mm', gaps);
            otherwise
                data = component_table.Data;
                keep = false(size(data, 1), 1);
                for data_row = 1:size(data, 1)
                    keep(data_row) = isnumeric(data{data_row, 2}) && ...
                        isfinite(data{data_row, 2}) && data{data_row, 2} > 0 && ...
                        isnumeric(data{data_row, 3}) && ...
                        isfinite(data{data_row, 3}) && data{data_row, 3} >= 0;
                end
                data = data(keep, :);
                if isempty(data)
                    error('pretest_planner_ui:noComponents', ...
                        ['Enter at least one measured spacer or foil thickness ' ...
                         'and its maximum count.']);
                end
                setup = struct('mode', 'combinations', ...
                    'component_names', {data(:, 1)'}, ...
                    'component_mm', cell2mat(data(:, 2))', ...
                    'maximum_counts', cell2mat(data(:, 3))');
        end
    end

    function lines = plan_review_lines(plan, input_messages)
        if plan.reliability_instruction_supported
            reliability_lines = [ ...
                "RELIABILITY SAFETY RULE"; ...
                sprintf([ ...
                    '%d independent articles before a supported reliability result.'], ...
                    plan.reliability_validation_floor_articles); ...
                "The main study can still estimate the middle gap and overall variation."];
        elseif strcmp(plan.reliability_instruction_status, ...
                'exploratory_confidence')
            reliability_lines = [ ...
                "EXPLORATORY CONFIDENCE"; ...
                "At 50% confidence or less, no safety-supported operating setting is issued."];
        else
            reliability_lines = [ ...
                "ABOVE RECORDED VALIDATION"; ...
                "Above 95% confidence, an estimate may be calculated but no safety-supported operating setting is issued."];
        end
        lines = [ ...
            "MAIN STUDY"; ...
            sprintf('%d separate articles', plan.main_articles); ...
            "Expected starting conditions."; ""; ...
            "RESERVE GROUP 1"; ...
            sprintf('%d articles - use only if the main checkpoint asks.', ...
                plan.reserve_1_articles); ""; ...
            "RESERVE GROUP 2"; ...
            sprintf('%d articles - use only if the next checkpoint asks.', ...
                plan.reserve_2_articles); ""; ...
            "TOTAL TO PREPARE"; ...
            sprintf('%d articles', plan.total_articles); ""; ...
            reliability_lines; ...
            "Reserve articles are not used automatically; you decide at each checkpoint."; ""; ...
            "FIRST REQUESTED GAP"; ...
            sprintf('%.2f mm', plan.starting_gap_mm); ""; ...
            "WHAT THESE ANSWERS ASSUME"; ...
            input_messages(:); plan.assumptions(:); ""; ...
            "WHAT TO REVIEW"; plan.suggestions(:); ""; ...
            "This is a pre-test estimate, not a reliability guarantee."];
    end

    function [plan, lines] = available_review(clean, reachable, estimate, input_messages)
        if isnan(estimate.best_reliability) || isnan(estimate.best_confidence)
            plan = [];
            lines = ["CURRENT ARTICLES"; ...
                sprintf('%d separate articles', clean.available_articles); ""; ...
                estimate.messages(:); ""; string(estimate.statement)];
            return;
        end
        requirements = clean;
        requirements.mode = 'requirements_first';
        requirements.reliability = estimate.best_reliability;
        requirements.confidence = estimate.best_confidence;
        plan = estimate_study_plan(requirements, reachable);
        plan.mode = 'available_articles_first';
        plan.available_articles = clean.available_articles;
        plan.fixed_kind = estimate.fixed_kind;
        plan.fixed_value = estimate.fixed_value;
        lines = [ ...
            "CURRENT ARTICLES"; sprintf('%d separate articles', clean.available_articles); ""; ...
            "PRE-TEST EXPECTATION"; ...
            sprintf('Reliability: %.1f%%', 100 * estimate.best_reliability); ...
            sprintf('Confidence: %.1f%%', 100 * estimate.best_confidence); ""; ...
            input_messages(:); estimate.messages(:); ""; string(estimate.statement)];
    end

    function save_plan()
        if isempty(state.current_plan), return; end
        [filename, folder] = uiputfile('*.json', 'Save study plan as');
        if isequal(filename, 0), return; end
        exact_path = fullfile(folder, filename);
        confirmation = uiconfirm(figure_handle, sprintf([ ...
            'This exact file will be created:\n\n%s\n\n' ...
            'An existing file will not be replaced.'], exact_path), ...
            'Confirm study-plan location', ...
            'Options', {'Create this plan', 'Choose again'}, ...
            'DefaultOption', 1, 'CancelOption', 2);
        if ~strcmp(confirmation, 'Create this plan'), return; end
        try
            saved_path = save_study_plan(state.current_plan, exact_path);
            state.selected_plan = state.current_plan;
            review_status.Text = ['Saved: ' saved_path];
            review_status.FontColor = color.teal;
            uialert(figure_handle, ['Study plan saved at:' newline saved_path], ...
                'Plan saved', 'Icon', 'success');
        catch save_error
            uialert(figure_handle, save_error.message, ...
                'Plan was not saved', 'Icon', 'warning');
        end
    end

    function close_planner()
        if isempty(state.selected_plan) && ~isempty(state.current_plan)
            state.selected_plan = state.current_plan;
        end
        uiresume(figure_handle);
    end
end
