function show_manual()
%SHOW_MANUAL Show the scrollable gap-study operator guide.

    color.graphite = [33 49 58] / 255;
    color.blue = [35 108 142] / 255;
    color.white = [247 249 250] / 255;
    color.paper = [1 1 1];
    fontName = 'Arial';

    figureHandle = uifigure('Name', 'Neyer Gap Test - Help', ...
        'Position', [250 70 900 760], 'Color', color.white);
    page = uigridlayout(figureHandle, [2 1]);
    page.RowHeight = {76, '1x'};
    page.Padding = [22 16 22 18];
    page.RowSpacing = 10;

    heading = uigridlayout(page, [2 1]);
    heading.RowHeight = {38, 28};
    heading.Padding = [4 0 4 0];
    heading.RowSpacing = 2;
    uilabel(heading, 'Text', 'Neyer Gap Test V2 - operator guide', ...
        'FontName', fontName, 'FontSize', 22, 'FontWeight', 'bold', ...
        'FontColor', color.graphite);
    uilabel(heading, 'Text', ...
        'Read the short sections below. Use the scroll bar to continue.', ...
        'FontName', fontName, 'FontSize', 13, ...
        'FontColor', color.blue);

    sections = help_sections();
    helpLayout = uigridlayout(page, [numel(sections) 1]);
    helpLayout.Tag = 'help_scroll_layout';
    helpLayout.Scrollable = 'on';
    helpLayout.RowHeight = {145, 380, 220, 280, 210, 145, 175, 290, 220};
    helpLayout.ColumnWidth = {'1x'};
    helpLayout.Padding = [4 4 16 8];
    helpLayout.RowSpacing = 12;

    for sectionNumber = 1:numel(sections)
        panel = uipanel(helpLayout, 'Title', sections(sectionNumber).title, ...
            'Tag', 'help_section', 'FontName', fontName, 'FontSize', 15, ...
            'FontWeight', 'bold', 'ForegroundColor', color.graphite, ...
            'BackgroundColor', color.paper);
        panel.Layout.Row = sectionNumber;
        panel.Layout.Column = 1;
        panelGrid = uigridlayout(panel, [1 1]);
        panelGrid.Padding = [16 10 16 12];
        paragraph = uilabel(panelGrid, 'Text', sections(sectionNumber).text, ...
            'Tag', 'help_paragraph', 'FontName', fontName, 'FontSize', 13, ...
            'FontColor', color.graphite, 'WordWrap', 'on', ...
            'VerticalAlignment', 'top');
        paragraph.Layout.Row = 1;
        paragraph.Layout.Column = 1;
    end
end

function sections = help_sections()
    sections(1) = section('What the tool answers', sprintf([ ...
        'This tool estimates how the chance of Interaction changes as the ' ...
        'physical gap changes. Smaller gaps make Interaction more likely; ' ...
        'larger gaps make No interaction more likely.\n\n' ...
        'Its main calculated answers are the middle gap (about 50%% ' ...
        'Interaction) and the overall variation (how gradual or sudden the ' ...
        'change is across similar articles). It can also report the estimated ' ...
        'chance of an outcome at one gap.']));

    sections(2) = section('What each direct input means', sprintf([ ...
        'Low middle-gap guess - the smallest reasonable starting location ' ...
        'of the 50/50 change. It is not the minimum test limit.\n\n' ...
        'High middle-gap guess - the largest reasonable starting location ' ...
        'of the 50/50 change.\n\n' ...
        'Rough overall-variation guess - a first estimate of how gradually ' ...
        'results change. Use 1 mm if only a broad first estimate is known.\n\n' ...
        'Maximum tests - the most new articles this run may use. It is not a ' ...
        'promise of confidence.\n\n' ...
        'Minimum permitted gap - the smallest gap the study may request. ' ...
        'Maximum permitted gap - the largest useful gap it may request.\n\n' ...
        'Unit - the distance unit used for every gap and variation value.\n\n' ...
        'How can you build the test gaps? - choose Regular gap step or ' ...
        'Confirmed gap list as explained in the next section.\n\n' ...
        'Foil thickness - construction information only. It does not set the ' ...
        'minimum gap or the usable step.\n\n' ...
        'No Pre-Test Planner result is required. Direct Run a Test is ' ...
        'independent from the separate Pre-Test Planner and does not read or ' ...
        'update a saved plan.']));

    sections(3) = section('Regular step versus confirmed list', sprintf([ ...
        'Regular gap step: choose this only when every multiple of the step ' ...
        'inside the permitted range can genuinely be built. Example: a ' ...
        '0.05 mm step means the tool may request any available 0.05 mm step.\n\n' ...
        'Confirmed gap list: choose this for a known set of measured, buildable ' ...
        'gaps. Enter each allowed value once, separated by commas; for example, ' ...
        '1.00, 1.10, 2.50. The tool requests only a value from that list.\n\n' ...
        'These are alternatives. Direct testing does not accept ' ...
        'spacer-combination recipes; only use physical settings already known ' ...
        'to be buildable.']));

    sections(4) = section('What to do for each new setup', sprintf([ ...
        '1. Build the requested gap shown on screen. The request uses two ' ...
        'decimal places, such as 5.00 mm; it is a build instruction, not the ' ...
        'measured gap.\n\n' ...
        '2. Measure the completed new setup once. Enter that one reading as ' ...
        'the measured gap. The calculation uses this measured value. Do not ' ...
        'average several readings for the setup.\n\n' ...
        '3. Perform one test on one new article. Select Interaction if the ' ...
        'defined interaction occurred; otherwise select No interaction.\n\n' ...
        '4. Treat the article and spacer setup as consumed by the destructive ' ...
        'test. If the same requested gap appears later, build another new ' ...
        'setup and take one new reading. Do not reuse the earlier value.']));

    sections(5) = section( ...
            'How to read unfinished and calculated results', sprintf([ ...
        'An unfinished result means the completed tests do not yet show both ' ...
        'outcomes close enough to calculate the change. The screen shows the ' ...
        'counts and a next action instead of blank charts or invented numbers. ' ...
        'Completed data can still be saved.\n\n' ...
        'A calculated result shows the middle gap and overall variation. The ' ...
        'middle gap is an about-50%% Interaction estimate, not automatically ' ...
        'an operating setting. Values outside the permitted range are reported ' ...
        'as outside the tested range, never as build instructions.']));

    sections(6) = section('Probability versus confidence', sprintf([ ...
        'Probability describes the estimated chance of Interaction or No ' ...
        'interaction at a chosen physical gap.\n\n' ...
        'Confidence describes how strongly the completed evidence supports ' ...
        'an estimate. It does not mean the chance that the next article has ' ...
        'that outcome. Report probability and confidence separately.']));

    sections(7) = section('Saving and reopening', sprintf([ ...
        'Save results... creates matching CSV data and an HTML report under ' ...
        'one base name. The app shows both destinations before saving. If ' ...
        'either file already exists, nothing is overwritten; choose a new name.\n\n' ...
        'While the main menu remains open, Review latest results reopens the ' ...
        'most recent run. Saved CSV and HTML files are permanent records for ' ...
        'review outside the app; they are not resumable test sessions.']));

    sections(8) = section( ...
            'Limits and the separate fixed-gap qualification concept', strjoin({ ...
        ['If one unexpected boundary result occurs at the minimum or maximum ' ...
        'permitted gap, the tool asks for one confirmation at that same gap ' ...
        'using a fresh setup. If it happens twice, the study pauses and keeps ' ...
        'the data for review. A pause is not a specimen outcome or a software ' ...
        'failure.'], ...
        ['The main study estimates the middle gap and overall variation. A ' ...
        'safety-supported reliability setting needs at least 400 independent articles. ' ...
        'Confidence of 50% or less is exploratory; no supported setting is issued. ' ...
        'Confidence above 95% can be calculated but is outside recorded validation.'], ...
        ['A fixed-gap qualification is a different study: first choose one gap, ' ...
        'then test a separately justified number of new, independent articles ' ...
        'at that fixed setting. This tool does not turn the changing-gap study ' ...
        'into that qualification or supply a universal qualification count.']}, ...
        [newline newline]));

    sections(9) = section('Method and traceability', sprintf([ ...
        'Stage 1 means the early search that moves outward to find where the ' ...
        'outcome changes. Stage 2 means the later search that concentrates ' ...
        'tests around that change.\n\n' ...
        'MLE means maximum-likelihood estimation: the calculation that finds ' ...
        'the middle gap and overall variation most consistent with the recorded ' ...
        'tests. D-optimal means the rule that chooses a useful next gap to add ' ...
        'the most information expected from one more test.\n\n' ...
        'These names provide traceability to the Neyer (1994) sensitivity-test ' ...
        'method. Operators can follow the earlier sections without using these ' ...
        'internal names.']));
end

function value = section(titleText, bodyText)
    value = struct('title', titleText, 'text', bodyText);
end
