function setup = validate_planner_components(component_names,component_mm,maximum_counts)
%VALIDATE_PLANNER_COMPONENTS Validate measured printed-spacer recipes.
% Foil recipes are intentionally unavailable until measured stacks and a
% practical maximum layer count have been supplied.

if ~iscell(component_names) || numel(component_names) ~= numel(component_mm) || ...
        numel(component_mm) ~= numel(maximum_counts) || isempty(component_mm) || ...
        any(~isfinite(component_mm)) || any(component_mm <= 0) || ...
        any(~isfinite(maximum_counts)) || any(maximum_counts < 0) || ...
        any(maximum_counts ~= floor(maximum_counts))
    error('validate_planner_components:badComponents', ...
        ['Enter measured printed-spacer thicknesses and whole-number ' ...
         'maximum counts.']);
end

names = string(component_names);
if any(contains(lower(names),'foil'))
    error('validate_planner_components:foilNotReady', ...
        ['Foil recipes are unavailable until foil stacks are measured and ' ...
         'a practical maximum layer count is confirmed.']);
end

setup = struct('mode','combinations', ...
    'component_names',{cellstr(names(:)')}, ...
    'component_mm',component_mm(:)', ...
    'maximum_counts',maximum_counts(:)');
end
