root=fileparts(mfilename('fullpath'));
results=runtests({fullfile(root,'tests','TestGapDirection.m'), ...
                  fullfile(root,'tests','TestGapBoundaryPause.m'), ...
                  fullfile(root,'tests','TestGapPresentation.m'), ...
                  fullfile(root,'tests','TestGapReliability.m'), ...
                  fullfile(root,'tests','TestPhysicalGapWorkflow.m'), ...
                  fullfile(root,'tests','TestPhysicalRunEntryPoint.m'), ...
                  fullfile(root,'tests','TestPhysicalUiInputs.m'), ...
                  fullfile(root,'tests','TestCombinedPhysicalStudy.m'), ...
                  fullfile(root,'tests','TestV19Delivery.m'), ...
                  fullfile(root,'tests','TestUiCaptureScript.m')});
disp(results);
assertSuccess(results);
