classdef TestV110Standalone < matlab.unittest.TestCase
    methods (Test)
        function candidateIsOneSelfContainedLiveScript(testCase)
            root = fileparts(fileparts(mfilename('fullpath')));
            live_script = fullfile(root, 'delivery', ...
                'Neyer_Gap_Test_v1_10.mlx');
            built_source = fullfile(root, 'delivery', ...
                'Neyer_Gap_Test_v1_10.m');

            testCase.assertTrue(isfile(live_script), ...
                'The v1.10 Live Script has not been built.');
            testCase.assertTrue(isfile(built_source), ...
                'The reviewable v1.10 build source has not been built.');

            text = fileread(built_source);
            forbidden = {'addpath(', 'C:\Users\', '.exe', ...
                'application/source', 'application\source'};
            for item = 1:numel(forbidden)
                testCase.verifyFalse(contains(text, forbidden{item}, ...
                    'IgnoreCase', true), sprintf( ...
                    'Standalone source contains forbidden dependency text: %s', ...
                    forbidden{item}));
            end

            required_words = {'MATLAB R2022b', 'Measured mean', ...
                'two decimal places', '400 independent articles', ...
                'not used automatically', 'never replaces an existing'};
            for item = 1:numel(required_words)
                testCase.verifyTrue(contains(text, required_words{item}, ...
                    'IgnoreCase', true), sprintf( ...
                    'Standalone instructions do not explain: %s', ...
                    required_words{item}));
            end

            source_files = dir(fullfile(root, 'application', 'source', '*.m'));
            for file_number = 1:numel(source_files)
                source_text = fileread(fullfile(source_files(file_number).folder, ...
                    source_files(file_number).name));
                declaration = regexp(source_text, ...
                    '(?m)^\s*function\s+(?:(?:\[[^\]]+\]|[A-Za-z]\w*)\s*=\s*)?([A-Za-z]\w*)', ...
                    'tokens', 'once');
                testCase.assertNotEmpty(declaration, sprintf( ...
                    'No function declaration found in %s.', ...
                    source_files(file_number).name));
                built_declarations = regexp(text, ...
                    ['(?m)^\s*function\s+(?:(?:\[[^\]]+\]|[A-Za-z]\w*)' ...
                    '\s*=\s*)?' declaration{1} '\s*\('], 'match');
                testCase.verifyNumElements(built_declarations, 1, sprintf( ...
                    'Function %s must be embedded exactly once.', declaration{1}));
            end
        end
    end
end
