classdef TestV2HelpUi < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addApplicationSource(testCase)
            projectRoot = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, 'application', 'source')));
        end
    end

    methods (TestMethodTeardown)
        function closeHelpWindow(~)
            delete(findall(groot, 'Type', 'figure', ...
                'Name', 'Neyer Gap Test - Help'));
        end
    end

    methods (Test)
        function limitsKeepWholeSentencesInThreeReadableParagraphs(testCase)
            figureHandle = open_help_window();
            panels = findall(figureHandle, 'Tag', 'help_section');
            panel = panels(string({panels.Title}) == ...
                "Limits and the separate fixed-gap qualification concept");
            label = findall(panel, 'Tag', 'help_paragraph');
            paragraphs = split(string(label.Text), string([newline newline]));
            testCase.verifyNumElements(paragraphs, 3, ...
                'Extra paragraph breaks can push required warnings outside the fixed-height panel.');
            testCase.verifySubstring(paragraphs(1), 'software failure.');
        end
        function helpUsesScrollableTitledSections(testCase)
            figureHandle = open_help_window();
            scrollLayout = findall(figureHandle, 'Tag', ...
                'help_scroll_layout');
            testCase.assertNumElements(scrollLayout, 1, ...
                'Help needs one identifiable scrollable layout.');
            testCase.verifyTrue(strcmp(scrollLayout.Scrollable, 'on'));

            panels = findall(figureHandle, 'Tag', 'help_section');
            titles = string({panels.Title});
            requiredTitles = [ ...
                "What the tool answers", ...
                "What each direct input means", ...
                "Regular step versus confirmed list", ...
                "What to do for each new setup", ...
                "How to read unfinished and calculated results", ...
                "Probability versus confidence", ...
                "Saving and reopening", ...
                "Limits and the separate fixed-gap qualification concept"];
            testCase.verifyTrue(all(ismember(requiredTitles, titles)), ...
                sprintf('Missing required help sections. Found: %s', ...
                strjoin(titles, ', ')));

            methodPanel = panels(titles == "Method and traceability");
            testCase.assertNumElements(methodPanel, 1);
            testCase.verifyEqual(methodPanel.Layout.Row, numel(panels), ...
                'Technical method definitions must be the final section.');
        end

        function helpExplainsThePhysicalWorkflowInOperatorWords(testCase)
            figureHandle = open_help_window();
            panels = findall(figureHandle, 'Tag', 'help_section');
            allText = visible_text(panels);
            requiredPhrases = [ ...
                "Low middle-gap guess", "High middle-gap guess", ...
                "Rough overall-variation guess", "Maximum tests", ...
                "Minimum permitted gap", "Maximum permitted gap", ...
                "Unit", "Foil thickness", ...
                "Regular gap step", "Confirmed gap list", ...
                "0.05 mm", "1.00, 1.10, 2.50", ...
                "no more than two decimal places", ...
                "requested gap", "two decimal places", ...
                "measured gap", "one reading", "new setup", ...
                "one test", "Interaction", "No interaction", ...
                "unfinished result", "calculated result", ...
                "Probability", "Confidence", "Save results...", ...
                "nothing is overwritten", "Review latest results", ...
                "not resumable test sessions", "separate Pre-Test Planner", ...
                "unexpected boundary result", "study pauses", ...
                "fixed-gap qualification", "400 independent articles", ...
                "50% or less", "above 95%"];
            for phraseNumber = 1:numel(requiredPhrases)
                testCase.verifySubstring(allText, requiredPhrases(phraseNumber));
            end
        end

        function operatorSectionsAvoidAndMethodSectionDefinesInternalTerms(testCase)
            figureHandle = open_help_window();
            panels = findall(figureHandle, 'Tag', 'help_section');
            testCase.assertNotEmpty(panels, ...
                'Help needs titled operator sections before jargon can be checked.');
            titles = string({panels.Title});
            methodPanel = panels(titles == "Method and traceability");
            testCase.assertNumElements(methodPanel, 1);
            operatorPanels = panels(titles ~= "Method and traceability");
            operatorText = visible_text(operatorPanels);
            internalTerms = ["Stage 1", "Stage 2", "MLE", "D-optimal"];
            for termNumber = 1:numel(internalTerms)
                testCase.verifyFalse(contains(operatorText, ...
                    internalTerms(termNumber)), sprintf( ...
                    'Operator sections contain internal term "%s".', ...
                    internalTerms(termNumber)));
            end

            methodText = visible_text(methodPanel);
            definitions = ["Stage 1 means", "Stage 2 means", ...
                "MLE means", "D-optimal means"];
            for definitionNumber = 1:numel(definitions)
                testCase.verifySubstring(methodText, ...
                    definitions(definitionNumber));
            end
        end

        function helpUsesWrappedProportionalTextInsteadOfTextAreaWall(testCase)
            figureHandle = open_help_window();
            testCase.verifyEmpty(findall(figureHandle, 'Type', 'uitextarea'));
            labels = findall(figureHandle, 'Type', 'uilabel', ...
                'Tag', 'help_paragraph');
            testCase.verifyGreaterThan(numel(labels), 8);
            testCase.verifyTrue(all(arrayfun( ...
                @(label) strcmp(label.WordWrap, 'on'), labels)));
            testCase.verifyFalse(any(arrayfun( ...
                @(label) strcmpi(label.FontName, 'Consolas'), labels)));
        end

    end
end

function figureHandle = open_help_window()
show_manual();
drawnow;
figureHandle = findall(groot, 'Type', 'figure', ...
    'Name', 'Neyer Gap Test - Help');
assert(numel(figureHandle) == 1, 'The Help window did not open.');
end

function text = visible_text(parents)
parts = strings(0, 1);
for parentNumber = 1:numel(parents)
    parts(end + 1, 1) = string(parents(parentNumber).Title); %#ok<AGROW>
    labels = findall(parents(parentNumber), 'Type', 'uilabel');
    for labelNumber = 1:numel(labels)
        parts(end + 1, 1) = string(labels(labelNumber).Text); %#ok<AGROW>
    end
end
text = strjoin(parts, newline);
end
