function outputFile=run_v19_reaudit_study(shardIndex,shardCount,repetitions)
%RUN_V19_REAUDIT_STUDY Run one repeatable shard of the V1.9 physical study.
%   Multiple MATLAB processes may call this function at the same time with
%   different shard indexes. Each process writes a separate checkpoint CSV.

if nargin<1 || isempty(shardIndex), shardIndex=1; end
if nargin<2 || isempty(shardCount), shardCount=1; end
if nargin<3 || isempty(repetitions), repetitions=300; end

root=fileparts(fileparts(mfilename('fullpath')));
evidenceFolder=fullfile(root,'audit','v19-reaudit');
if ~isfolder(evidenceFolder), mkdir(evidenceFolder); end
outputFile=fullfile(evidenceFolder,sprintf( ...
    'v19-reaudit-shard-%d-of-%d.csv',shardIndex,shardCount));

options=struct( ...
    'output_file',outputFile, ...
    'budgets',[20 50], ...
    'true_sigmas',[0.10 0.20 0.50], ...
    'increments',[0.05 0.10], ...
    'floor_factors',[0 1 2], ...
    'reading_sds',[0.015 0.030], ...
    'reading_counts',[4 5], ...
    'build_sd_factors',[0 0.25 0.50], ...
    'grid_points',1001, ...
    'seed',20260912, ...
    'use_parallel',false, ...
    'scenario_shard_index',shardIndex, ...
    'scenario_shard_count',shardCount);

run_combined_physical_study(repetitions,options);
end
