param([string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot))

$ErrorActionPreference = 'Stop'
$out = Join-Path $ProjectRoot 'delivery\Neyer_Gap_Test_v1_9_Report.html'
$shotRoot = Join-Path $ProjectRoot 'assets\screenshots'
$simulationSummaryPath = Join-Path $ProjectRoot 'audit\v19-reaudit\v19-reaudit-simulation-summary.csv'
$testSummaryPath = Join-Path $ProjectRoot 'audit\v19-reaudit\v19-reaudit-test-summary.txt'
if (-not (Test-Path -LiteralPath $simulationSummaryPath)) { throw "Missing corrected simulation evidence: $simulationSummaryPath" }
if (-not (Test-Path -LiteralPath $testSummaryPath)) { throw "Missing current test evidence: $testSummaryPath" }
$simulationSummary = @(Import-Csv -LiteralPath $simulationSummaryPath)
$testSummaryText = Get-Content -LiteralPath $testSummaryPath -Raw
$passedTests = [regex]::Match($testSummaryText,'Passed: (\d+)').Groups[1].Value
if (-not $passedTests) { throw 'Could not read the verified MATLAB test count.' }

function F([object]$value,[int]$digits=2) {
    return ([double]$value).ToString("F$digits",[Globalization.CultureInfo]::InvariantCulture)
}

$physicalRows = foreach ($budget in @(20,50)) {
    foreach ($floor in @(0,1,2)) {
        $rows = @($simulationSummary | Where-Object { [int]$_.budget -eq $budget -and [double]$_.floor_factor -eq $floor })
        if ($rows.Count -ne 2) { throw "Expected two corrected increment summaries for budget $budget and floor $floor." }
        $actual = ($rows | Measure-Object -Property actual_strict_overlap_percent -Average).Average
        $falsePct = ($rows | Measure-Object -Property false_overlap_percent -Average).Average
        $middle = [Math]::Sqrt((($rows | ForEach-Object { [Math]::Pow([double]$_.middle_gap_rmse,2) }) | Measure-Object -Average).Average)
        $width = [Math]::Sqrt((($rows | ForEach-Object { [Math]::Pow([double]$_.transition_width_rmse,2) }) | Measure-Object -Average).Average)
        $label = if ($floor -eq 0) { 'None' } else { "$floor × increment" }
        $class = if ($floor -eq 2) { ' class="good"' } else { '' }
        "<tr><td>$budget</td><td>$label</td><td>21,600</td><td$class>$(F $actual 2)%</td><td>$(F $falsePct 3)%</td><td>$(F $middle 3) mm</td><td>$(F $width 3) mm</td></tr>"
    }
}

function ImageData([string]$name) {
    $path = Join-Path $shotRoot $name
    if (-not (Test-Path -LiteralPath $path)) { throw "Missing report image: $path" }
    $bytes = [System.IO.File]::ReadAllBytes($path)
    return 'data:image/png;base64,' + [Convert]::ToBase64String($bytes)
}

$menu = ImageData '01-main-menu.png'
$settings = ImageData '02-settings.png'
$testGap = ImageData '03-test-gap.png'
$results = ImageData '04-results.png'
$help = ImageData '05-help.png'

$html = @"
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Neyer Gap Test v1.9 | Audit and delivery report</title>
<style>
:root{--ink:#142738;--navy:#173b57;--blue:#26739b;--teal:#23837b;--amber:#d98a2b;--silver:#e8edf0;--line:#c7d1d7;--paper:#fbfcfd;--muted:#526775}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.58 "Segoe UI",Arial,sans-serif}a{color:#125f87}header{background:linear-gradient(115deg,#102c41,#1d5777);color:white;padding:72px 6vw 58px}header .inner,main{max-width:1160px;margin:auto}.kicker{font-size:15px;font-weight:650;letter-spacing:.04em;color:#c5e6f4}h1{font-size:clamp(42px,6vw,72px);line-height:1.02;margin:14px 0 20px;max-width:900px}header p{max-width:780px;font-size:21px;color:#e7f2f7}.rule{height:8px;margin-top:38px;background:linear-gradient(90deg,var(--amber) 0 39%,#f4c875 39% 50%,var(--teal) 50% 100%)}main{padding:46px 24px 90px}nav{background:#edf3f5;border:1px solid var(--line);padding:22px 26px;margin-bottom:20px}nav strong{display:block;font-size:21px;margin-bottom:9px}nav a{display:inline-block;margin:4px 18px 4px 0;font-weight:600}section{padding:38px 0;border-bottom:1px solid var(--line);scroll-margin-top:18px}h2{font-size:34px;line-height:1.15;margin:0 0 18px}h3{font-size:22px;margin:22px 0 8px}p{max-width:820px}.lead{font-size:21px;color:var(--muted)}.status{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;margin-top:24px}.status div{border-top:5px solid var(--teal);padding:16px 0}.status strong{font-size:30px;display:block}.flow{display:grid;grid-template-columns:repeat(3,1fr);gap:0;margin:26px 0}.flow article{padding:24px;border-top:6px solid var(--blue);background:#f0f5f7}.flow article:nth-child(2){background:#e6eff3;border-color:var(--amber)}.flow article:nth-child(3){background:#dbeaed;border-color:var(--teal)}.flow b{font-size:24px}.gapline{margin:30px 0;padding:22px 0;position:relative}.gapline:before{content:"";position:absolute;left:0;right:0;top:49%;height:6px;background:linear-gradient(90deg,var(--amber),#e7d9aa 48%,var(--teal))}.gapline span{position:relative;display:inline-block;background:var(--paper);padding:5px 12px;font-weight:700}.gapline .right{float:right}table{width:100%;border-collapse:collapse;margin:20px 0 28px;font-size:16px}th{background:var(--navy);color:white;text-align:left}th,td{padding:12px 14px;border:1px solid var(--line);vertical-align:top}tr:nth-child(even) td{background:#f0f4f6}.good{color:#08746b;font-weight:700}.warn{color:#9a5b09;font-weight:700}.visual{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px;margin-top:22px}.visual figure{margin:0}.visual img{width:100%;display:block;border:1px solid #aebcc4;box-shadow:0 10px 30px rgba(20,39,56,.12)}figcaption{font-size:14px;color:var(--muted);margin-top:8px}.callout{border-left:7px solid var(--amber);background:#f8f0df;padding:18px 22px;margin:24px 0;max-width:900px}.checks{columns:2;column-gap:40px}.checks li{margin-bottom:8px}.small{font-size:14px;color:var(--muted)}code{background:#edf2f4;padding:2px 5px;border-radius:3px}@media(max-width:760px){.status,.flow,.visual{grid-template-columns:1fr}.checks{columns:1}header{padding-top:48px}h2{font-size:29px}}
</style></head><body>
<header><div class="inner"><div class="kicker">MATLAB R2022b • completed engineering build</div><h1>Neyer Gap Test v1.9</h1><p>A plain-language record of the algorithm audit, physical-gap changes, simulation evidence, and final standalone verification.</p><div class="rule"></div></div></header>
<main>
<nav aria-label="Report contents"><strong>Report contents</strong><a href="#executive-summary">Summary</a><a href="#objective-scope">Objective</a><a href="#original-tool">Original tool</a><a href="#audit-method">Audit method</a><a href="#audit-findings">Findings</a><a href="#fixes-improvements">Fixes</a><a href="#testing">Testing</a><a href="#operation">Operation</a><a href="#saving">Saving</a><a href="#file-structure">Files</a><a href="#limitations">Limitations</a><a href="#conclusion">Conclusion</a></nav>
<section id="executive-summary"><h2>Executive summary</h2><div class="status"><div><strong>1 file</strong>Standalone MATLAB Live Script</div><div><strong>$passedTests / $passedTests</strong>Regression tests passed</div><div><strong>129,600</strong>Corrected physical simulation runs reviewed</div></div><p class="lead">V1.9 corrects the Neyer Stage-1 and Stage-2 logic, applies the 0.8 Stage-2 shrink, respects physical gap resolution, records measured gaps, and pauses safely on repeated boundary contradictions. The Live Script was tested by itself in a newly created empty folder. Its embedded demo returned 5.3922 mm for the middle gap and 1.0412 mm for the transition width.</p></section>

<section id="objective-scope"><h2>Project objective and scope</h2><div class="gapline"><span>Small gap<br>interaction likely</span><span class="right">Large gap<br>interaction unlikely</span></div><p>The objective was to audit the MATLAB Neyer implementation without altering its original file, reproduce its reference-table behaviour, separate real algorithm discrepancies from deliberate engineering choices, and then build a physically usable gap-test version. The method learns two quantities from destructive Go/No-Go tests. The <b>middle gap</b> is where interaction is about 50%. The <b>transition width</b> describes how quickly the response changes around that middle.</p><div class="flow"><article><b>Stage 1</b><p>Search outward, then close the response bracket until its width reaches one guessed transition width.</p></article><article><b>Stage 2</b><p>Choose informative reachable gaps. Reduce the working width by 0.8 after each test until outcomes overlap.</p></article><article><b>Stage 3</b><p>Fit the middle and width, then choose later tests by D-optimal information.</p></article></div></section>

<section id="original-tool"><h2>Description of the original V1.8 tool</h2><p>The preserved V1.8 Live Script reproduced Neyer's published Table 1 and provided a working three-stage sensitivity test. Its core probit maximum-likelihood calculation and D-optimal information determinant agreed with the method in principle. However, reproducing one published sequence did not exercise every decision branch. Several choices—especially the 1.5 sigma Stage-2 transition—were reconstruction choices rather than rules established by the paper.</p></section>

<section id="audit-method"><h2>How the audit was performed</h2><ol><li>Preserved V1.8 and recorded its SHA-256 fingerprint.</li><li>Created regression tests for the published reference-table sequence before changing behaviour.</li><li>Compared Stage 1, both parts of Stage 2, maximum-likelihood fitting, D-optimal selection, bounds, rounding, and stopping logic with the documented Neyer process.</li><li>Added focused tests for every corrected decision branch.</li><li>Ran synthetic Go/No-Go studies, including physical increments, repeated readings, measurement noise, new spacer-build variation, test budgets, and sigma-floor choices.</li><li>Built and tested the final `.mlx` by itself from a clean MATLAB start.</li></ol></section>

<section id="audit-findings"><h2>Audit findings, ordered by importance</h2><table><thead><tr><th>Importance</th><th>Area</th><th>V1.8 finding</th><th>Why it mattered</th></tr></thead><tbody>
<tr><td class="warn">Major</td><td>Stage 1</td><td>Simplified doubling reproduced the reference table but did not implement the full bound-aware paper rule.</td><td>Different starting ranges could select the wrong next test.</td></tr>
<tr><td class="warn">Major</td><td>Stage 2 transition</td><td>The 1.5 × sigma threshold came from reconstructing the table, not Neyer's rule.</td><td>It could leave bisection too early.</td></tr>
<tr><td class="warn">Major</td><td>0.8 shrink</td><td>The setting existed but the decision loop never used it.</td><td>Later Stage-2 requests did not tighten as intended.</td></tr>
<tr><td class="warn">Major</td><td>Stage 2 state</td><td>An early correction could return from D-optimal testing to bisection.</td><td>That contradicted the one-way transition and could repeat old behaviour.</td></tr>
<tr><td>Important</td><td>Rounding</td><td>Two decimals reproduced Table 1 but did not represent every tool increment.</td><td>The app could request a gap the equipment cannot build.</td></tr>
<tr><td>Important</td><td>Bounds and stopping</td><td>Repeated boundary clamping could look like a loop.</td><td>An operator needed a safe review pause, not a false failure.</td></tr>
<tr><td>Confirmed</td><td>MLE</td><td>Core probit likelihood and positive sigma parameterisation matched. Extreme tails still need deeper numerical study.</td><td>The core was retained; the remaining limit is disclosed.</td></tr>
<tr><td>Confirmed</td><td>D-optimal selection</td><td>The information determinant matched Neyer. Grid and ±5 sigma fence were engineering choices.</td><td>The mathematical selection core could be preserved.</td></tr></tbody></table>
<div class="callout"><b>Why Table 1 could hide the Stage 2 error</b><br>The first D-optimal test created overlap immediately. The reference sequence therefore never exercised a second Stage-2 test, where the missing 0.8 shrink would have become visible.</div></section>

<section id="fixes-improvements"><h2>Fixes and improvements applied</h2><table><thead><tr><th>Change</th><th>Final V1.9 behaviour</th></tr></thead><tbody><tr><td>Correct Stage 1</td><td>Uses the full bound-aware reach rule in the correct decreasing-gap direction.</td></tr><tr><td>Correct Stage 2</td><td>Part 1 changes at 1.0 guessed sigma; Part 2 is one-way and shrinks its working sigma by 0.8 after every separated result.</td></tr><tr><td>Physical requests</td><td>Chooses the nearest different reachable and useful setting.</td></tr><tr><td>Actual gap evidence</td><td>Requires 4 or 5 readings from each new spacer build and uses their measured mean.</td></tr><tr><td>Resolution protection</td><td>Defaults to a working-sigma floor of twice the confirmed equipment increment.</td></tr><tr><td>Safe stopping</td><td>Confirms an unexpected boundary once, then pauses and preserves the run.</td></tr><tr><td>Safe saving</td><td>Shows both complete output paths before saving and never silently replaces an existing result.</td></tr></tbody></table></section>

<section><h2>Physical test workflow</h2><table><thead><tr><th>Term</th><th>Meaning</th><th>How V1.9 uses it</th></tr></thead><tbody>
<tr><td>Requested gap</td><td>The mathematical best next point.</td><td>Kept for audit history.</td></tr><tr><td>Reachable gap</td><td>The nearest different setting the spacer system can build and that can still help create overlap.</td><td>Shown to the operator.</td></tr><tr><td>Measured mean</td><td>The average of 4 or 5 readings taken on the newly built spacer setup.</td><td>Used as the statistical gap for that physical build.</td></tr></tbody></table>
<p>Every destructive test uses a new spacer build. The operator measures that unchanged build four or five times before testing it. Repeated readings describe measurement variation. They do not remove build-to-build variation, so the simulation includes both effects.</p></section>

<section id="testing"><h2>Testing and verification evidence</h2><p class="lead">The equipment increment matters most when it is close to the true transition width.</p><table><thead><tr><th>True transition width</th><th>0.01 mm step</th><th>0.05 mm step</th><th>0.10 mm step</th><th>0.25 mm step</th></tr></thead><tbody>
<tr><td>0.10 mm</td><td>83.5%</td><td>65.5%</td><td>46.0%</td><td>3.5%</td></tr><tr><td>0.20 mm</td><td>92.5%</td><td>86.5%</td><td>79.0%</td><td>35.5%</td></tr><tr><td>0.50 mm</td><td>100%</td><td>98.5%</td><td>98.0%</td><td>84.0%</td></tr><tr><td>1.00 mm</td><td>99.5%</td><td>99.0%</td><td>99.0%</td><td>92.5%</td></tr></tbody></table>
<p class="small">Values show the percentage of simulations achieving strict overlap within 20 tests. Source: <code>increment-study-results.csv</code>, 32 cells × 200 repetitions.</p></section>

<section><h2>Corrected physical simulation</h2><p>The final combined study covered test budgets of 20 and 50, true widths, 0.05 and 0.10 mm increments, four and five readings, two reading-noise levels, build-to-build variation, and three sigma-floor settings. It contained 432 scenarios × 300 repetitions.</p><div class="callout"><b>Important evidence correction</b><br>The earlier simulator varied and measured the built gap but used the requested setting to decide Interaction or No interaction. The application was not affected. This rerun decides each synthetic outcome from the actual built gap, and the values below replace the earlier percentages.</div><table><thead><tr><th>Test budget</th><th>Sigma floor</th><th>Runs</th><th>Actual overlap</th><th>False overlap</th><th>Middle RMSE</th><th>Width RMSE</th></tr></thead><tbody>
$($physicalRows -join "`n")</tbody></table>
<div class="callout"><b>Decision used in V1.9</b><br>The 2 × increment floor prevents the working Stage-2 width from shrinking below twice the confirmed physical increment. The corrected comparison above shows its measured effect without claiming that simulation replaces physical qualification.</div></section>

<section><h2>Boundary and stopping logic</h2><p>The permitted study range defaults to 0–10 mm for this gap setup. A surprising no-interaction result at 0 mm, or interaction at 10 mm, receives one confirmation test at the same boundary. If the contradiction repeats, V1.9 pauses for review and preserves the run. It does not label the experiment a statistical failure.</p><p>Confidence limits outside 0–10 mm remain in the scientific record as raw mathematical results, but the interface does not present them as buildable settings.</p></section>

<section><h2>MATLAB interface</h2><div class="visual"><figure><img src="$menu" alt="Neyer Gap Test main menu"><figcaption>Main menu</figcaption></figure><figure><img src="$settings" alt="Physical gap input screen"><figcaption>Study settings with required physical increment</figcaption></figure><figure><img src="$testGap" alt="Requested gap and measurement entry"><figcaption>Reachable gap and 4–5 measurement entry</figcaption></figure><figure><img src="$results" alt="Neyer gap study results"><figcaption>Results, interaction curve, and reliability calculator</figcaption></figure><figure><img src="$help" alt="Neyer Gap Test help"><figcaption>Built-in operating instructions</figcaption></figure></div></section>

<section id="operation"><h2>How to operate V1.9</h2><ol><li>Open <code>Neyer_Gap_Test_v1_9.mlx</code> in MATLAB R2022b.</li><li>Run the Live Script. The <b>Neyer Gap Test</b> menu opens.</li><li>Use <b>Run a Demo (verify)</b> first. It should show 5.3922 mm and 1.0412 mm.</li><li>Select <b>Run a Test</b>, enter the 0–10 mm study range, guessed transition width, test count, unit, and confirmed physical increment.</li><li>For each requested reachable gap, build a new spacer setup, measure it four or five times, enter all readings, then record Interaction or No interaction.</li><li>Save the final CSV and HTML results from the results window.</li></ol><p><b>Accepted inputs:</b> finite numeric range values with maximum above minimum; positive guessed width; a whole-number test count; a short unit label; and a confirmed 0.05 mm or 0.10 mm increment. Missing, invalid, or incomplete entries produce a plain-language error.</p></section>

<section id="saving"><h2>Where result data are saved</h2><p>The tool does not use a hidden fixed folder. The operator selects a folder and base name in the save window. Before writing, the app displays the complete intended paths for both outputs:</p><ul><li><code>&lt;selected folder&gt;\&lt;chosen name&gt;.csv</code> — complete test data.</li><li><code>&lt;selected folder&gt;\&lt;chosen name&gt;.html</code> — self-contained result report and chart.</li></ul><p>If either file already exists, the app writes neither file and asks the operator to choose another name. This prevents silent loss of an earlier test.</p></section>

<section><h2>Verification record</h2><ul class="checks"><li>MATLAB R2022b parser accepted the source.</li><li>All 80 source functions had unique names.</li><li>The delivered source uses no <code>addpath</code>.</li><li>The `.mlx` ran alone in an empty folder.</li><li>The actual Demo button produced the reference estimates.</li><li>$passedTests regression tests passed.</li><li>0 tests failed or remained incomplete.</li><li>Existing-file protection was tested for both CSV and HTML.</li><li>V1.8 source and preserved copy hashes still match.</li><li>No executable, internet connection, or add-on package is required.</li></ul><p class="small">Code Analyzer notes are advisory readability and callback-detection messages, not parse failures. Runtime tests are the acceptance evidence.</p></section>

<section id="file-structure"><h2>Final file and folder structure</h2><table><thead><tr><th>Location</th><th>Contents</th></tr></thead><tbody><tr><td>OneDrive top level</td><td>The final `.mlx`, `.pptx`, and `.html` deliverables.</td></tr><tr><td>Repository <code>application/</code></td><td>The final standalone Live Script and readable MATLAB source.</td></tr><tr><td>Repository <code>tests/</code></td><td>Regression and physical-workflow checks.</td></tr><tr><td>Repository <code>audit/</code></td><td>Audit evidence and simulation summaries.</td></tr><tr><td>Repository <code>deliverables/</code></td><td>Copies of the three final deliverables.</td></tr><tr><td>Repository <code>tools/</code></td><td>Repeatable build and verification scripts.</td></tr></tbody></table></section>

<section id="limitations"><h2>Known limits and operator decisions</h2><ul><li>The true equipment increment still needs physical confirmation. Choose 0.05 mm or 0.10 mm only after checking the tool.</li><li>The method estimates population response. It cannot remove unknown spacer construction bias or measurement calibration bias.</li><li>Extreme-data MLE convergence deserves a separate deep numerical study if this tool becomes a safety-critical qualification method.</li><li>Four or five readings describe one newly built spacer; destructive tests still introduce build-to-build variation.</li></ul></section>

<section><h2>Preservation and source</h2><p>The original V1.8 file remains unchanged. Its SHA-256 hash is <code>C2D709060E1F784535960F27682586F66C8E908C6EF90C8DF035CE099646C424</code>.</p><p>Method reference: Barry T. Neyer, “A D-Optimality-Based Sensitivity Test,” <i>Technometrics</i> 36(1), 61–70 (1994), DOI <a href="https://doi.org/10.1080/00401706.1994.10485401">10.1080/00401706.1994.10485401</a>.</p></section>
<section id="conclusion"><h2>Conclusion</h2><p>The audit, algorithm corrections, physical-gap workflow, resolution study, safe stopping, safe saving, standalone MATLAB build, presentation, and report are complete. The final decision rules are supported by regression tests and the recorded synthetic simulation evidence. The remaining equipment-resolution confirmation and extreme-data numerical study are clearly disclosed rather than presented as completed work.</p></section>
</main></body></html>
"@

[System.IO.File]::WriteAllText($out,$html,[System.Text.UTF8Encoding]::new($false))
Write-Output "Built $out"
Write-Output "Bytes: $((Get-Item -LiteralPath $out).Length)"
