function combine_v113_audit_simulations(shardCount)
%COMBINE_V113_AUDIT_SIMULATIONS Join independently executed audit shards.
if nargin < 1, shardCount = 4; end
projectRoot = fileparts(fileparts(mfilename('fullpath')));
outputFolder = fullfile(projectRoot, 'audit', 'v113-complete');
summary = table();
performanceShards = table();
for shardIndex = 1:shardCount
    shard = readtable(fullfile(outputFolder, sprintf( ...
        'simulation-shard-%d-of-%d.csv', shardIndex, shardCount)));
    shardPerformance = readtable(fullfile(outputFolder, sprintf( ...
        'performance-shard-%d-of-%d.csv', shardIndex, shardCount)));
    summary = [summary; shard]; %#ok<AGROW>
    performanceShards = [performanceShards; shardPerformance]; %#ok<AGROW>
end
summary = sortrows(summary, 'scenario');
assert(height(summary) == 360 && numel(unique(summary.scenario)) == 360, ...
    'The four simulation shards did not contain all 360 unique scenarios.');
writetable(summary, fullfile(outputFolder, 'simulation-summary.csv'));
performance = table(string(version('-release')), "four-process", 4, ...
    height(summary), unique(summary.repetitions), ...
    sum(performanceShards.total_runs), max(performanceShards.elapsed_seconds), ...
    median(summary.median_run_seconds), max(summary.maximum_run_seconds), ...
    sum(summary.invariant_failures), sum(~summary.replay_matches), ...
    'VariableNames', {'matlab_release','execution_mode','workers', ...
    'scenario_count','repetitions_per_scenario','total_runs', ...
    'elapsed_seconds','median_scenario_run_seconds', ...
    'maximum_scenario_run_seconds','invariant_failures', ...
    'replay_mismatches'});
writetable(performance, fullfile(outputFolder, 'performance-summary.csv'));
fprintf(['V1.13 COMBINED SIMULATION AUDIT: %d scenarios, %d runs, ' ...
    '%d invariant failures, %d replay mismatches.\n'], height(summary), ...
    performance.total_runs, performance.invariant_failures, ...
    performance.replay_mismatches);
assert(performance.invariant_failures == 0 && ...
    performance.replay_mismatches == 0, ...
    'The combined simulation audit found a failure.');
end
