project_root = fileparts(fileparts(mfilename('fullpath')));
cd(project_root);
test_files = { ...
    fullfile(project_root,'tests','TestPhysicalUiInputs.m'), ...
    fullfile(project_root,'tests','TestPhysicalGapWorkflow.m'), ...
    fullfile(project_root,'tests','TestPhysicalRunEntryPoint.m'), ...
    fullfile(project_root,'tests','TestGapPresentation.m'), ...
    fullfile(project_root,'tests','TestV19IndependentReaudit.m'), ...
    fullfile(project_root,'measurement-recorder','tests','TestMeasurementRecord.m')};
results = runtests(test_files);
disp(table(results));
if any([results.Failed]) || any([results.Incomplete])
    exit(1);
end
exit(0);
