project_root = fileparts(fileparts(mfilename('fullpath')));
cd(project_root);

group_names = [ ...
    "Original algorithm and reference table"; ...
    "Stage logic and next-gap selection"; ...
    "Pre-test planner and checkpoints"; ...
    "Physical build and measurement entry"; ...
    "Reliability results and safe rounding"; ...
    "Saving, reopening, and overwrite protection"; ...
    "Standalone v1.10 file"];

group_purposes = [ ...
    "Preserves the recorded V1.8 reference behavior and checks the published equations."; ...
    "Checks Stage 1, the 0.8 narrowing rule, overlap, fitted estimates, useful next gaps, bounds, rounding, and stopping."; ...
    "Checks both planner routes, confidence classes, article reserves, physical capability, and unsupported requests."; ...
    "Checks 4 or 5 readings, measured-mean use, fresh builds, mismatched requested and measured gaps, and boundary pauses."; ...
    "Checks decreasing-gap direction, operating instructions, plots, confidence calculations, and out-of-range protection."; ...
    "Checks user-selected paths, plan reopening, full saved data, and refusal to replace existing files."; ...
    "Checks that the Live Script contains every function and has no outside code dependency."];

test_groups = { ...
    {'TestBaselineCharacterization.m','TestReferenceTable.m','TestPaperConformance.m'}; ...
    {'TestStage1Only.m','TestTransitionOnly.m','TestShrinkOnly.m', ...
     'TestProposedNeyer.m','TestResolutionAwareStage2.m'}; ...
    {'TestPreTestPlanner.m','TestStudyCheckpoint.m','TestPlannerSimulation.m', ...
     'TestPlannerUiSource.m','TestReachableGapModel.m'}; ...
    {'TestPhysicalGapWorkflow.m','TestPhysicalRunEntryPoint.m', ...
     'TestPhysicalUiInputs.m','TestGapBoundaryPause.m','TestCombinedPhysicalStudy.m'}; ...
    {'TestGapDirection.m','TestGapReliability.m','TestGapPresentation.m', ...
     'TestResultDecision.m','TestFixedGapConfidence.m'}; ...
    {'TestStudyPlanStorage.m'}; ...
    {'TestV110Standalone.m'}};

rows = table('Size', [numel(group_names), 8], ...
    'VariableTypes', {'string','string','double','double','double','double','string','string'}, ...
    'VariableNames', {'route','purpose','test_methods','passed','failed', ...
    'incomplete','status','matlab_release'});
all_passed = true;
for group_number = 1:numel(group_names)
    files = test_groups{group_number};
    suite = testsuite(fullfile(project_root, 'tests', files{1}));
    for file_number = 2:numel(files)
        suite = [suite testsuite(fullfile(project_root, 'tests', ...
            files{file_number}))]; %#ok<AGROW>
    end
    group_result = run(suite);
    passed = sum([group_result.Passed]);
    failed = sum([group_result.Failed]);
    incomplete = sum([group_result.Incomplete]);
    if failed == 0 && incomplete == 0
        status = "passed";
    else
        status = "failed";
        all_passed = false;
    end
    rows(group_number, :) = {group_names(group_number), ...
        group_purposes(group_number), numel(group_result), passed, failed, ...
        incomplete, status, string(version('-release'))};
end

csv_path = fullfile(project_root, 'audit', 'overnight', ...
    'mock-lab-results.csv');
summary_path = fullfile(project_root, 'audit', 'overnight', ...
    'full-test-summary.txt');
writetable(rows, csv_path);
file_id = fopen(summary_path, 'w');
assert(file_id >= 0, 'Could not create the overnight test summary.');
fprintf(file_id, 'Neyer v1.10 complete mock laboratory verification\n');
fprintf(file_id, 'MATLAB release: %s\n', version('-release'));
fprintf(file_id, 'Routes: %d\n', height(rows));
fprintf(file_id, 'Test methods: %d\n', sum(rows.test_methods));
fprintf(file_id, 'Passed: %d\n', sum(rows.passed));
fprintf(file_id, 'Failed: %d\n', sum(rows.failed));
fprintf(file_id, 'Incomplete: %d\n', sum(rows.incomplete));
fprintf(file_id, 'Every destructive-test route treats each article as a new build.\n');
fprintf(file_id, 'Four or five readings describe one unchanged build; their mean is the fitted gap.\n');
fclose(file_id);

if ~all_passed
    exit(1);
end
exit(0);
