function run_five_direct_62_trials()
%RUN_FIVE_DIRECT_62_TRIALS Audit five planner-free 62-test physical studies.
% This verification uses the production direct-test parser, sequential Neyer
% loop, maximum-likelihood fit, confidence calculation, and reachable-gap
% selection. It does not call or load the Pre-Test Planner.

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root, 'application', 'source'));
evidence_folder = fullfile(project_root, 'audit', 'direct-62-trials');
if ~isfolder(evidence_folder), mkdir(evidence_folder); end

usable_steps = [0.05 0.10 0.15 0.25 0.50];
trial_seeds = 202609081:202609085;
test_budget = 62;
minimum_gap = 1.00;
maximum_gap = 10.00;
true_middle = 2.50;
true_overall_variation = 0.50;
build_standard_deviation = 0.02;
reading_standard_deviation = 0.01;
readings_per_build = 1;

summary_rows = repmat(empty_summary_row(), numel(usable_steps), 1);
trajectory_rows = repmat(empty_trajectory_row(), ...
    numel(usable_steps) * test_budget, 1);
trajectory_row = 0;

% These arrays are shared with the nested physical-response function. They
% are replaced for every trial, so every requested test uses a new virtual
% article, a new build error, and one new measurement error.
current_thresholds = zeros(test_budget, 1);
current_build_errors = zeros(test_budget, 1);
current_reading_errors = zeros(readings_per_build, test_budget);
current_actual_gaps = NaN(test_budget, 1);
current_minimum_gap = minimum_gap;
current_maximum_gap = maximum_gap;

for trial_number = 1:numel(usable_steps)
    usable_step = usable_steps(trial_number);
    seed = trial_seeds(trial_number);
    rng(seed, 'twister');
    current_thresholds = true_middle + ...
        true_overall_variation * randn(test_budget, 1);
    current_build_errors = build_standard_deviation * randn(test_budget, 1);
    current_reading_errors = reading_standard_deviation * ...
        randn(readings_per_build, test_budget);
    current_actual_gaps = NaN(test_budget, 1);

    answers = {'1', '10', '1', '62', '1', '10', 'mm', ...
        sprintf('%.2f', usable_step), '0.015'};
    parsed = parse_run_inputs(answers);
    row = empty_summary_row();
    row.trial = trial_number;
    row.seed = seed;
    row.usable_gap_step_mm = usable_step;
    try
        no_planner = ~isfield(parsed.cfg, 'study_plan') || ...
            isempty(parsed.cfg.study_plan);
        [result, record] = run_physical_test(parsed.params, ...
            parsed.num_parts, @physical_response, parsed.cfg);
        audit = audit_one_trial(record, result, parsed.cfg, ...
            current_actual_gaps(1:record.N), ...
            current_thresholds(1:record.N), ...
            true_middle, true_overall_variation, no_planner);

        row.completed_tests = record.N;
        row.run_status = string(record.status);
        row.interactions = sum(record.successes);
        row.no_interactions = sum(~record.successes);
        row.stage1_count = sum(record.stage == 1);
        row.stage2_count = sum(record.stage == 2);
        row.stage3_count = sum(record.stage == 3);
        row.first_stage2_test = first_or_nan(find(record.stage == 2, 1));
        row.first_stage3_test = first_or_nan(find(record.stage == 3, 1));
        row.immediate_duplicate_requests = audit.immediate_duplicates;
        row.out_of_bounds_requests = audit.out_of_bounds;
        row.off_grid_requests = audit.off_grid;
        row.fitted_middle_mm = result.mu;
        row.middle_error_mm = result.mu - true_middle;
        row.fitted_overall_variation_mm = result.sigma;
        row.overall_variation_error_mm = ...
            result.sigma - true_overall_variation;
        row.middle_95_lower_mm = result.mu_lo;
        row.middle_95_upper_mm = result.mu_hi;
        row.middle_truth_inside_95 = audit.middle_truth_covered;
        row.variation_95_lower_mm = result.sigma_lo;
        row.variation_95_upper_mm = result.sigma_hi;
        row.variation_truth_inside_95 = audit.variation_truth_covered;
        row.expected_interactions_from_truth = ...
            audit.expected_interactions_from_truth;
        row.observed_minus_expected_interactions = ...
            audit.observed_minus_expected_interactions;
        row.standardized_outcome_balance = audit.standardized_outcome_balance;
        row.mean_build_error_mm = audit.mean_build_error;
        row.mean_measurement_error_mm = audit.mean_measurement_error;
        row.truth_likelihood_distance = audit.truth_likelihood_distance;
        row.truth_inside_joint_95 = audit.truth_inside_joint_95;
        row.maximum_doptimal_raw_difference_mm = ...
            audit.maximum_doptimal_raw_difference;
        row.all_hard_checks_passed = audit.all_hard_checks_passed;
        row.audit_message = string(audit.message);

        for test_number = 1:record.N
            trajectory_row = trajectory_row + 1;
            trajectory_rows(trajectory_row) = struct( ...
                'trial', trial_number, 'seed', seed, ...
                'usable_gap_step_mm', usable_step, ...
                'test_number', test_number, ...
                'raw_requested_gap_mm', record.raw_requested_levels(test_number), ...
                'requested_gap_mm', record.requested_levels(test_number), ...
                'actual_gap_mm', current_actual_gaps(test_number), ...
                'measured_gap_mm', record.levels(test_number), ...
                'article_threshold_mm', current_thresholds(test_number), ...
                'outcome', outcome_text(record.successes(test_number)), ...
                'stage', record.stage(test_number), ...
                'incoming_middle_mm', record.est_mu(test_number), ...
                'incoming_overall_variation_mm', record.est_sigma(test_number));
        end
    catch trial_error
        row.run_status = "audit_error";
        row.all_hard_checks_passed = false;
        row.audit_message = string(sprintf('%s: %s', ...
            trial_error.identifier, trial_error.message));
    end
    summary_rows(trial_number) = row;
end

trajectory_rows = trajectory_rows(1:trajectory_row);
summary_table = struct2table(summary_rows);
trajectory_table = struct2table(trajectory_rows);
summary_path = fullfile(evidence_folder, 'five-trial-summary.csv');
trajectory_path = fullfile(evidence_folder, 'five-trial-trajectories.csv');
audit_path = fullfile(evidence_folder, 'five-trial-audit.txt');
plot_path = fullfile(evidence_folder, 'five-trial-comparison.png');
writetable(summary_table, summary_path);
writetable(trajectory_table, trajectory_path);
write_plain_audit(audit_path, summary_table, true_middle, ...
    true_overall_variation, build_standard_deviation, ...
    reading_standard_deviation, readings_per_build);
write_comparison_plot(plot_path, summary_table, true_middle, ...
    true_overall_variation);

fprintf('\nFive direct 62-test trials completed.\n');
fprintf('Summary: %s\n', summary_path);
fprintf('Trajectories: %s\n', trajectory_path);
fprintf('Audit: %s\n', audit_path);
fprintf('Visual: %s\n', plot_path);

if ~all(summary_table.all_hard_checks_passed)
    failed_rows = find(~summary_table.all_hard_checks_passed);
    error('run_five_direct_62_trials:auditFailed', ...
        'Hard audit checks failed for trial(s): %s.', ...
        strjoin(string(failed_rows), ', '));
end

    function response = physical_response(requested_gap, test_number)
        actual_gap = requested_gap + current_build_errors(test_number);
        actual_gap = min(max(actual_gap, current_minimum_gap), ...
            current_maximum_gap);
        readings = actual_gap + current_reading_errors(test_number);
        current_actual_gaps(test_number) = actual_gap;
        response = struct( ...
            'outcome', actual_gap <= current_thresholds(test_number), ...
            'measurements', readings);
    end
end

function audit = audit_one_trial(record, result, cfg, actual_gaps, ...
        thresholds, true_middle, true_variation, no_planner)
tolerance = 1e-9;
requested = record.requested_levels(:);
measured = record.levels(:);
successes = logical(record.successes(:));
candidates = cfg.reachable_model.gaps_mm(:);

budget_ok = record.requested_N == 62 && record.N == 62 && ...
    strcmp(record.status, 'complete');
out_of_bounds = sum(requested < cfg.min_level - tolerance | ...
    requested > cfg.max_level + tolerance);
distance_to_reachable = arrayfun(@(gap) min(abs(candidates - gap)), ...
    requested);
off_grid = sum(distance_to_reachable > ...
    cfg.reachable_model.comparison_tolerance_mm);
immediate_duplicates = sum(abs(diff(requested)) <= ...
    cfg.reachable_model.comparison_tolerance_mm);
checkpoint_free = isempty(record.checkpoint_decisions);

measurement_count_ok = all(cellfun(@numel, record.measurements) == 1);
measurement_values = cellfun(@double, record.measurements);
measurement_value_ok = max(abs(measurement_values(:) - measured)) <= 1e-12;
outcomes_match_actual = isequal(successes, actual_gaps(:) <= thresholds(:));

stage_values_ok = all(ismember(record.stage, [1 2 3]));
first_stage2 = find(record.stage == 2, 1);
first_stage3 = find(record.stage == 3, 1);
one_way_stage2 = true;
transition_ok = true;
shrink_ok = true;
if ~isempty(first_stage2)
    one_way_stage2 = ~any(record.stage(first_stage2:end) == 1);
    previous_levels = measured(1:first_stage2 - 1);
    previous_outcomes = successes(1:first_stage2 - 1);
    bracket_width = min(previous_levels(~previous_outcomes)) - ...
        max(previous_levels(previous_outcomes));
    transition_limit = cfg.stage2_bisect_width_sigmas * ...
        record.params.sigma_guess;
    transition_ok = bracket_width <= transition_limit + 1e-10;

    stage2_rows = find(record.stage == 2);
    if numel(stage2_rows) > 1
        shrink_floor = record.resolution_sigma_floor;
        for position = 2:numel(stage2_rows)
            previous_row = stage2_rows(position - 1);
            current_row = stage2_rows(position);
            if current_row ~= previous_row + 1
                shrink_ok = false;
                break;
            end
            expected_sigma = max(cfg.stage2_shrink * ...
                record.est_sigma(previous_row), shrink_floor);
            if abs(record.est_sigma(current_row) - expected_sigma) > 1e-10
                shrink_ok = false;
                break;
            end
        end
    end
end
if ~isempty(first_stage3)
    one_way_stage3 = all(record.stage(first_stage3:end) == 3);
else
    one_way_stage3 = false;
end

reachable_mapping_ok = true;
for test_number = 1:record.N
    allowed = true(size(candidates));
    if test_number > 1
        allowed = abs(candidates - requested(test_number - 1)) > ...
            cfg.reachable_model.comparison_tolerance_mm;
    end
    rows = find(allowed);
    [~, nearest_position] = min(abs(candidates(rows) - ...
        record.raw_requested_levels(test_number)));
    expected_request = candidates(rows(nearest_position));
    if abs(requested(test_number) - expected_request) > tolerance
        reachable_mapping_ok = false;
        break;
    end
end

doptimal_ok = true;
maximum_doptimal_raw_difference = 0;
stage3_rows = find(record.stage == 3);
for position = 1:numel(stage3_rows)
    test_number = stage3_rows(position);
    [expected_raw, determinant] = pick_next_level( ...
        measured(1:test_number - 1), record.est_mu(test_number), ...
        record.est_sigma(test_number), cfg);
    difference = abs(expected_raw - ...
        record.raw_requested_levels(test_number));
    maximum_doptimal_raw_difference = max( ...
        maximum_doptimal_raw_difference, difference);
    if difference > tolerance || ~isfinite(determinant) || determinant <= 0
        doptimal_ok = false;
        break;
    end
end

fit_exists = result.has_overlap && isfinite(result.mu) && ...
    isfinite(result.sigma) && result.sigma > 0;
fit_matches = false;
likelihood_stable = false;
truth_likelihood_distance = NaN;
truth_inside_joint_95 = false;
if fit_exists
    [raw_mu, raw_sigma, likelihood_one] = best_fit(measured, successes, ...
        record.est_mu(end), record.est_sigma(end));
    [expected_mu, expected_sigma] = sanity_clamp(raw_mu, raw_sigma, ...
        measured, cfg);
    [~, ~, likelihood_two] = best_fit(measured, successes, ...
        true_middle, true_variation);
    fit_matches = abs(result.mu - expected_mu) <= 1e-8 && ...
        abs(result.sigma - expected_sigma) <= 1e-8;
    likelihood_stable = abs(likelihood_one - likelihood_two) <= 1e-7;
    truth_likelihood = loglik(measured, successes, true_middle, ...
        true_variation);
    truth_likelihood_distance = 2 * (likelihood_one - truth_likelihood);
    % For two fitted quantities, 5.991 is the usual 95% likelihood-ratio
    % boundary. This is descriptive for one run, not a hard pass rule.
    truth_inside_joint_95 = truth_likelihood_distance <= 5.991;
end

truth_probabilities = shape_model(actual_gaps, true_middle, true_variation);
expected_interactions_from_truth = sum(truth_probabilities.p);
observed_minus_expected_interactions = sum(successes) - ...
    expected_interactions_from_truth;
outcome_variance = sum(truth_probabilities.p .* (1 - truth_probabilities.p));
standardized_outcome_balance = observed_minus_expected_interactions / ...
    sqrt(outcome_variance);
mean_build_error = mean(actual_gaps - requested);
mean_measurement_error = mean(measured - actual_gaps);

confidence_order_ok = all(isfinite([result.mu_lo result.mu_hi ...
    result.sigma_lo result.sigma_hi])) && ...
    result.mu_lo <= result.mu_hi && result.sigma_lo > 0 && ...
    result.sigma_lo <= result.sigma_hi;
middle_truth_covered = confidence_order_ok && ...
    result.mu_lo <= true_middle && true_middle <= result.mu_hi;
variation_truth_covered = confidence_order_ok && ...
    result.sigma_lo <= true_variation && true_variation <= result.sigma_hi;

hard_checks = [no_planner budget_ok out_of_bounds == 0 off_grid == 0 ...
    immediate_duplicates == 0 checkpoint_free measurement_count_ok ...
    measurement_value_ok outcomes_match_actual stage_values_ok ...
    ~isempty(first_stage2) one_way_stage2 transition_ok shrink_ok ...
    one_way_stage3 reachable_mapping_ok doptimal_ok fit_exists ...
    fit_matches likelihood_stable confidence_order_ok];
all_hard_checks_passed = all(hard_checks);
if all_hard_checks_passed
    message = 'PASS';
else
    labels = ["no planner", "62 completed", "inside bounds", ...
        "on reachable grid", "no immediate duplicates", ...
        "no checkpoints", "one reading", "reading used directly", ...
        "outcome uses actual gap", "valid stages", "Stage 2 reached", ...
        "Stage 2 one-way", "1.0-sigma transition", "0.8 shrink", ...
        "Stage 3 one-way", "nearest reachable mapping", ...
        "D-optimal raw choice", "fitted result", "fit matches MLE", ...
        "MLE stable from two starts", "ordered finite confidence ranges"];
    message = char("Failed: " + strjoin(labels(~hard_checks), ', '));
end

audit = struct('all_hard_checks_passed', all_hard_checks_passed, ...
    'message', message, 'immediate_duplicates', immediate_duplicates, ...
    'out_of_bounds', out_of_bounds, 'off_grid', off_grid, ...
    'middle_truth_covered', middle_truth_covered, ...
    'variation_truth_covered', variation_truth_covered, ...
    'expected_interactions_from_truth', expected_interactions_from_truth, ...
    'observed_minus_expected_interactions', ...
        observed_minus_expected_interactions, ...
    'standardized_outcome_balance', standardized_outcome_balance, ...
    'mean_build_error', mean_build_error, ...
    'mean_measurement_error', mean_measurement_error, ...
    'truth_likelihood_distance', truth_likelihood_distance, ...
    'truth_inside_joint_95', truth_inside_joint_95, ...
    'maximum_doptimal_raw_difference', ...
        maximum_doptimal_raw_difference);
end

function write_plain_audit(path, summary, true_middle, true_variation, ...
        build_standard_deviation, reading_standard_deviation, readings_per_build)
file_id = fopen(path, 'w');
assert(file_id >= 0, 'Could not create the five-trial audit file.');
cleanup = onCleanup(@() fclose(file_id)); %#ok<NASGU>
fprintf(file_id, 'Five direct Run-a-Test trials: logic and mathematics audit\n');
fprintf(file_id, 'MATLAB release: %s\n', version('-release'));
fprintf(file_id, 'Pre-Test Planner used: NO\n');
fprintf(file_id, 'Tests requested per trial: 62\n');
fprintf(file_id, 'True middle gap: %.2f mm\n', true_middle);
fprintf(file_id, 'True overall variation: %.2f mm\n', true_variation);
fprintf(file_id, 'New-build variation used: %.2f mm standard deviation\n', ...
    build_standard_deviation);
fprintf(file_id, 'Measurement variation used: %.2f mm standard deviation\n', ...
    reading_standard_deviation);
fprintf(file_id, 'Readings from each unchanged build: %d\n\n', ...
    readings_per_build);
for row = 1:height(summary)
    fprintf(file_id, ['Trial %d | step %.2f mm | tests %d | middle %.4f mm | ' ...
        'variation %.4f mm | Stage 1/2/3 %d/%d/%d | hard audit %s\n'], ...
        summary.trial(row), summary.usable_gap_step_mm(row), ...
        summary.completed_tests(row), summary.fitted_middle_mm(row), ...
        summary.fitted_overall_variation_mm(row), ...
        summary.stage1_count(row), summary.stage2_count(row), ...
        summary.stage3_count(row), ...
        char(pass_text(summary.all_hard_checks_passed(row))));
    fprintf(file_id, '  %s\n', char(summary.audit_message(row)));
    fprintf(file_id, ['  Outcome balance: observed minus expected %.2f ' ...
        '(standardized %.2f); truth inside joint 95%% region: %s\n'], ...
        summary.observed_minus_expected_interactions(row), ...
        summary.standardized_outcome_balance(row), ...
        char(pass_text(summary.truth_inside_joint_95(row))));
end
fprintf(file_id, '\nHard checks covered:\n');
fprintf(file_id, ['- no planner or planner checkpoints\n- bounds and reachable gaps\n' ...
    '- no accidental immediate duplicate request\n- one measured gap used directly\n' ...
    '- outcome generated from the actual built gap\n- Stage-2 1.0-sigma entry and 0.8 shrink\n' ...
    '- one-way stage movement\n- D-optimal raw selection\n' ...
    '- positive maximum-likelihood fit stable from two starting points\n' ...
    '- finite, ordered 95%% ranges for middle and overall variation\n']);
fprintf(file_id, ['\nConfidence coverage is reported, not used as a hard pass rule. ' ...
    'A correct 95%% method can miss the true value in an occasional single run.\n']);
fprintf(file_id, ['Five runs audit the recorded logic and calculations; they do not ' ...
    'by themselves prove long-run performance for every material or spacer system.\n']);
end

function write_comparison_plot(path, summary, true_middle, true_variation)
figure_handle = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [100 100 1000 720]);
cleanup = onCleanup(@() close(figure_handle)); %#ok<NASGU>
layout = tiledlayout(figure_handle, 2, 1, 'TileSpacing', 'compact', ...
    'Padding', 'compact');
title(layout, ['Five planner-free direct trials: 62 virtual articles each'], ...
    'FontWeight', 'bold');

nexttile(layout);
middle_lower_error = summary.fitted_middle_mm - summary.middle_95_lower_mm;
middle_upper_error = summary.middle_95_upper_mm - summary.fitted_middle_mm;
errorbar(summary.usable_gap_step_mm, summary.fitted_middle_mm, ...
    middle_lower_error, middle_upper_error, 'o-', 'LineWidth', 1.6, ...
    'MarkerFaceColor', [0.13 0.42 0.55]);
hold on;
yline(true_middle, '--', 'True middle = 2.50 mm', 'LineWidth', 1.4);
grid on;
xlabel('Usable gap step (mm)');
ylabel('Estimated middle gap (mm)');
title('Middle-gap estimate and 95% range');

nexttile(layout);
variation_lower_error = summary.fitted_overall_variation_mm - ...
    summary.variation_95_lower_mm;
variation_upper_error = summary.variation_95_upper_mm - ...
    summary.fitted_overall_variation_mm;
errorbar(summary.usable_gap_step_mm, ...
    summary.fitted_overall_variation_mm, variation_lower_error, ...
    variation_upper_error, 's-', 'LineWidth', 1.6, ...
    'MarkerFaceColor', [0.18 0.49 0.40]);
hold on;
yline(true_variation, '--', 'True variation = 0.50 mm', ...
    'LineWidth', 1.4);
grid on;
xlabel('Usable gap step (mm)');
ylabel('Estimated overall variation (mm)');
title('Overall-variation estimate and 95% range');
exportgraphics(figure_handle, path, 'Resolution', 150);
end

function value = first_or_nan(value)
if isempty(value), value = NaN; end
end

function text = outcome_text(is_interaction)
if is_interaction, text = "Interaction"; else, text = "No interaction"; end
end

function text = pass_text(passed)
if passed, text = "PASS"; else, text = "FAIL"; end
end

function row = empty_summary_row()
row = struct('trial', NaN, 'seed', NaN, 'usable_gap_step_mm', NaN, ...
    'completed_tests', 0, 'run_status', "not_run", ...
    'interactions', 0, 'no_interactions', 0, ...
    'stage1_count', 0, 'stage2_count', 0, 'stage3_count', 0, ...
    'first_stage2_test', NaN, 'first_stage3_test', NaN, ...
    'immediate_duplicate_requests', NaN, 'out_of_bounds_requests', NaN, ...
    'off_grid_requests', NaN, 'fitted_middle_mm', NaN, ...
    'middle_error_mm', NaN, 'fitted_overall_variation_mm', NaN, ...
    'overall_variation_error_mm', NaN, 'middle_95_lower_mm', NaN, ...
    'middle_95_upper_mm', NaN, 'middle_truth_inside_95', false, ...
    'variation_95_lower_mm', NaN, 'variation_95_upper_mm', NaN, ...
    'variation_truth_inside_95', false, ...
    'expected_interactions_from_truth', NaN, ...
    'observed_minus_expected_interactions', NaN, ...
    'standardized_outcome_balance', NaN, 'mean_build_error_mm', NaN, ...
    'mean_measurement_error_mm', NaN, 'truth_likelihood_distance', NaN, ...
    'truth_inside_joint_95', false, ...
    'maximum_doptimal_raw_difference_mm', NaN, ...
    'all_hard_checks_passed', false, 'audit_message', "not run");
end

function row = empty_trajectory_row()
row = struct('trial', NaN, 'seed', NaN, 'usable_gap_step_mm', NaN, ...
    'test_number', NaN, 'raw_requested_gap_mm', NaN, ...
    'requested_gap_mm', NaN, 'actual_gap_mm', NaN, ...
    'measured_gap_mm', NaN, 'article_threshold_mm', NaN, ...
    'outcome', "", 'stage', NaN, 'incoming_middle_mm', NaN, ...
    'incoming_overall_variation_mm', NaN);
end
