projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'application', 'source'));
addpath(fullfile(projectRoot, 'tools'));
evidenceFolder = fullfile(projectRoot, 'audit', 'v113-complete');
if ~isfolder(evidenceFolder), mkdir(evidenceFolder); end

scenarios = audit_math_scenarios();
candidateGaps = (0:0.05:10)';
rows = cell(size(scenarios, 1), 1);
for scenarioNumber = 1:size(scenarios, 1)
    scenarioName = scenarios{scenarioNumber, 1};
    gaps = scenarios{scenarioNumber, 2};
    interaction = scenarios{scenarioNumber, 3};
    oracle = v113_independent_oracle(gaps, interaction, ...
        candidateGaps, 0.95, [min(gaps); mean(gaps); max(gaps)]);
    [productionMiddle, productionVariation] = best_fit(gaps, interaction, ...
        mean(gaps), std(gaps));
    productionConfidence = lr_confidence(gaps, interaction, ...
        productionMiddle, productionVariation, neyer_settings());

    [history0, history1, history2] = info_terms(gaps, oracle.mu, oracle.sigma);
    [candidate0, candidate1, candidate2] = info_terms( ...
        candidateGaps, oracle.mu, oracle.sigma);
    productionDeterminant = (sum(history0) + candidate0) .* ...
        (sum(history2) + candidate2) - (sum(history1) + candidate1).^2;
    [~, winner] = max(productionDeterminant);
    productionDOptimalGap = candidateGaps(winner);

    productionMiddleConfidence = [productionConfidence.mu_lo, ...
        productionConfidence.mu_hi];
    productionVariationConfidence = [productionConfidence.sigma_lo, ...
        productionConfidence.sigma_hi];
    rows{scenarioNumber} = table(string(scenarioName), numel(gaps), ...
        productionMiddle, oracle.mu, abs(productionMiddle - oracle.mu), ...
        productionVariation, oracle.sigma, ...
        abs(productionVariation - oracle.sigma), ...
        max(abs(productionMiddleConfidence - oracle.mu_ci)), ...
        max(abs(productionVariationConfidence - oracle.sigma_ci)), ...
        productionDOptimalGap, oracle.d_optimal_gap, ...
        productionDOptimalGap == oracle.d_optimal_gap, ...
        'VariableNames', {'scenario', 'tests', 'v113_middle_mm', ...
        'independent_middle_mm', 'middle_absolute_difference_mm', ...
        'v113_variation_mm', 'independent_variation_mm', ...
        'variation_absolute_difference_mm', ...
        'middle_confidence_max_difference_mm', ...
        'variation_confidence_max_difference_mm', ...
        'v113_d_optimal_gap_mm', 'independent_d_optimal_gap_mm', ...
        'd_optimal_choice_matches'});
end
comparisonTable = vertcat(rows{:});
writetable(comparisonTable, fullfile(evidenceFolder, ...
    'math-comparisons.csv'));

assert(all(comparisonTable.middle_absolute_difference_mm < 2e-4));
assert(all(comparisonTable.variation_absolute_difference_mm < 2e-4));
assert(all(comparisonTable.d_optimal_choice_matches));
fprintf('V1.13 MATH COMPARISON: %d varied histories matched the independent oracle.\n', ...
    height(comparisonTable));

function scenarios = audit_math_scenarios()
paperGaps = [1.00; 1.20; 1.40; 1.80; 2.60; 4.20; 3.40; 3.80; 4.00; ...
    4.10; 4.28; 4.52; 5.55; 5.24; 6.37; 6.08; 7.38; 7.09; 6.89; 6.74];
paperInteraction = logical([1; 1; 1; 1; 1; 0; 1; 1; 1; 1; 1; 1; ...
    0; 1; 0; 1; 0; 0; 0; 0]);
scenarios = {
    'paper replay', paperGaps, paperInteraction;
    'balanced', [3; 4; 4.5; 5; 5.5; 6; 7], ...
        logical([1; 1; 0; 1; 1; 0; 0]);
    'narrow', [4.70; 4.80; 4.90; 5.00; 5.10; 5.20; 5.30], ...
        logical([1; 1; 0; 1; 0; 0; 0]);
    'wide', [1; 2; 3; 4; 5; 6; 7; 8; 9], ...
        logical([1; 0; 1; 1; 0; 1; 0; 0; 0]);
    'duplicate gaps', [3; 4; 4; 5; 5; 6; 6; 7], ...
        logical([1; 1; 0; 1; 0; 1; 0; 0]);
    'near physical boundaries', [0; 0.10; 0.20; 0.50; 1; 9; 9.50; 9.80; 9.90; 10], ...
        logical([1; 1; 0; 1; 1; 0; 0; 1; 0; 0])
    };
end
