project_root=fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root,'simulation'));
output_file=fullfile(project_root,'audit','v113', ...
    'varied-physical-validation.csv');
options=struct( ...
    'output_file',output_file, ...
    'budgets',62, ...
    'true_sigmas',[0.25 0.50 1.00 1.50], ...
    'increments',[0.05 0.10 0.15 0.50], ...
    'floor_factors',2, ...
    'reading_sds',0.01, ...
    'reading_counts',1, ...
    'build_sd_factors',0.20, ...
    'grid_points',1001, ...
    'seed',202609146, ...
    'use_parallel',true, ...
    'parallel_workers',8);

run_combined_physical_study(100,options);

results=readtable(output_file);
manifest_file=fullfile(project_root,'audit','v113', ...
    'varied-physical-validation-manifest.txt');
file_id=fopen(manifest_file,'w');
assert(file_id>=0,'Could not create the varied-study manifest.');
cleanup=onCleanup(@()fclose(file_id)); %#ok<NASGU>
fprintf(file_id,'V1.13 varied physical validation\n');
fprintf(file_id,'Executed: %s\n',char(datetime('now','TimeZone','Asia/Dubai', ...
    'Format','yyyy-MM-dd HH:mm:ss Z')));
fprintf(file_id,'MATLAB release: %s\n',version('-release'));
fprintf(file_id,'Runner: tools/run_v113_varied_physical_validation.m\n');
fprintf(file_id,'Scenarios: %d\n',height(results));
fprintf(file_id,'Repetitions per scenario: 100\n');
fprintf(file_id,'Total runs: %d\n',100*height(results));
fprintf(file_id,'Budget: 62\n');
fprintf(file_id,'True overall variations: 0.25, 0.50, 1.00, 1.50 mm\n');
fprintf(file_id,'Usable steps: 0.05, 0.10, 0.15, 0.50 mm\n');
fprintf(file_id,'One reading per new build; reading SD 0.01 mm\n');
fprintf(file_id,'New-build SD: 0.20 times the usable step\n');
fprintf(file_id,'Stage-2 floor: 2 usable steps\n');
fprintf(file_id,'Seed: 202609146\n');
fprintf(file_id,'Recorded execution mode: %s\n',char(results.execution_mode(1)));
fprintf(file_id,'V1.13 Live Script SHA-256: %s\n',sha256_file( ...
    fullfile(project_root,'delivery','Neyer_Gap_Test_v1_13.mlx')));
fprintf(file_id,'choose_stage.m SHA-256: %s\n',sha256_file( ...
    fullfile(project_root,'application','source','choose_stage.m')));
fprintf(file_id,'select_reachable_request.m SHA-256: %s\n',sha256_file( ...
    fullfile(project_root,'application','source','select_reachable_request.m')));
fprintf(file_id,'run_loop.m SHA-256: %s\n',sha256_file( ...
    fullfile(project_root,'application','source','run_loop.m')));
fprintf(file_id,'Results CSV SHA-256: %s\n',sha256_file(output_file));

function hash_text=sha256_file(path)
file_id=fopen(path,'r');
assert(file_id>=0,'Could not read %s for fingerprinting.',path);
cleanup=onCleanup(@()fclose(file_id)); %#ok<NASGU>
bytes=fread(file_id,Inf,'*uint8');
digest=java.security.MessageDigest.getInstance('SHA-256');
digest.update(bytes);
hash_text=upper(reshape(dec2hex(typecast(digest.digest(),'uint8'),2).',1,[]));
end
