projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'application', 'source'));
evidenceFolder = fullfile(projectRoot, 'audit', 'v113-complete');
if ~isfolder(evidenceFolder), mkdir(evidenceFolder); end
rows = cell(0, 7);

for usableStep = [0.05 0.10 0.15 0.50]
    model = reachable_gap_model(struct('mode', 'regular', ...
        'increment_mm', usableStep), 0, 10);
    [selected, status] = select_reachable_request(2.45, model, [], false);
    passed = strcmp(status.code, 'ok') && ...
        any(abs(model.gaps_mm - selected) < 1e-10) && ...
        ~isempty(regexp(char(status.display_gap), '^\d+\.\d{2} mm$', 'once'));
    rows(end + 1, :) = {'Regular reachable step', ...
        sprintf('%.2f mm step', usableStep), 'raw request 2.45 mm', ...
        'listed reachable gap shown to two decimals', ...
        char(status.display_gap), passed, status.message}; %#ok<AGROW>
end

confirmed = [0; 0.50; 1.10; 2.07; 2.57; 3.17; 4.14; 10.00];
model = reachable_gap_model(struct('mode', 'list', ...
    'gaps_mm', confirmed), 0, 10);
for rawRequest = [0.24 0.80 1.95 2.45 3.80 8.00]
    [selected, status] = select_reachable_request(rawRequest, model, [], false);
    passed = any(abs(confirmed - selected) < 1e-12);
    rows(end + 1, :) = {'Confirmed irregular list', ...
        sprintf('raw %.2f mm', rawRequest), sprintf('%.4g', rawRequest), ...
        'one value from the confirmed list', sprintf('%.4g', selected), ...
        passed, status.message}; %#ok<AGROW>
end

settings = neyer_settings();
settings.usable_resolution = 0.05;
settings.level_increment = 0.05;
parameters = struct('avg_low', 0, 'avg_high', 4.90, 'spread_guess', 0.5);
response = @(~, ~) struct('outcome', true, 'measurements', 2.50);
[~, measuredRecord] = run_physical_test(parameters, 3, response, settings);
passed = abs(measuredRecord.requested_levels(1) - 2.45) < 1e-12 && ...
    abs(measuredRecord.levels(1) - 2.50) < 1e-12;
rows(end + 1, :) = {'Requested versus measured', 'single reading', ...
    'request 2.45; measure 2.50', ...
    'store request 2.45 and analyze 2.50', ...
    sprintf('request %.2f; analysis %.2f', ...
    measuredRecord.requested_levels(1), measuredRecord.levels(1)), ...
    passed, 'The measured physical gap drives the statistics.'};

badEntries = {'', 'word', '-0.01', '2.49 2.50', 'NaN', 'Inf'};
for entryNumber = 1:numel(badEntries)
    caught = false;
    identifier = '';
    try
        parse_physical_response(badEntries{entryNumber}, true);
    catch problem
        caught = strcmp(problem.identifier, ...
            'parse_physical_response:badMeasurements');
        identifier = problem.identifier;
    end
    rows(end + 1, :) = {'Measurement validation', ...
        sprintf('invalid entry %d', entryNumber), badEntries{entryNumber}, ...
        'clear rejection', identifier, caught, ...
        'No invalid value reached the statistical history.'}; %#ok<AGROW>
end

model = reachable_gap_model(struct('mode', 'list', ...
    'gaps_mm', [0.30 0.35]), 0.30, 0.35);
settings = neyer_settings();
settings.min_level = 0.30;
settings.max_level = 0.35;
settings.usable_resolution = 0.05;
settings.reachable_model = model;
settings.stage2_bisect_width_sigmas = 2;
parameters = struct('avg_low', 0.20, 'avg_high', 0.40, ...
    'spread_guess', 0.03);
outcomes = logical([true; false]);
response = @(gap, testNumber) struct('outcome', outcomes(testNumber), ...
    'measurements', gap);
[pauseResult, pauseRecord] = run_physical_test(parameters, 3, response, settings);
passed = strcmp(pauseRecord.status, 'paused') && pauseRecord.N == 2 && ...
    strcmp(pauseResult.status, 'paused');
rows(end + 1, :) = {'Stopping', 'no different useful setting', ...
    'two reachable gaps exhausted', 'pause and preserve two tests', ...
    sprintf('%s after %d tests', pauseRecord.status, pauseRecord.N), ...
    passed, 'A pause is not labelled as a failed physical article.'};

for usableStep = [0.05 0.10 0.15 0.50]
    settings = neyer_settings();
    settings.usable_resolution = usableStep;
    parameters = struct('avg_low', 0, 'avg_high', 10, ...
        'spread_guess', 1);
    response = @(gap, ~) struct('outcome', gap < 5, 'measurements', gap);
    [~, floorRecord] = run_physical_test(parameters, 4, response, settings);
    expectedFloor = 2 * usableStep;
    passed = abs(floorRecord.resolution_sigma_floor - expectedFloor) < 1e-12;
    rows(end + 1, :) = {'Variation floor', ...
        sprintf('%.2f mm usable step', usableStep), ...
        sprintf('%.2f', usableStep), sprintf('%.2f', expectedFloor), ...
        sprintf('%.2f', floorRecord.resolution_sigma_floor), passed, ...
        'Physical runs keep the approved two-step planning floor.'}; %#ok<AGROW>
end

physicalMatrix = cell2table(rows, 'VariableNames', {'category', ...
    'case_name', 'input', 'expected', 'observed', 'pass', 'notes'});
writetable(physicalMatrix, fullfile(evidenceFolder, ...
    'physical-gap-matrix.csv'));
assert(all(physicalMatrix.pass), 'At least one physical gap audit case failed.');
fprintf('V1.13 PHYSICAL MATRIX: %d cases passed.\n', height(physicalMatrix));
