function summary = v114_simulate_study(true_middle_mm, true_variation_mm, ...
        usable_step_mm, maximum_tests, random_seed)
%V114_SIMULATE_STUDY Run one reproducible first-study synthetic experiment.

values = [true_middle_mm, true_variation_mm, usable_step_mm, ...
    maximum_tests, random_seed];
if any(~isfinite(values)) || true_variation_mm <= 0 || ...
        usable_step_mm <= 0 || maximum_tests < 3 || ...
        maximum_tests ~= floor(maximum_tests)
    error('v114_simulate_study:badInput', ...
        'Simulation inputs must be finite and physically meaningful.');
end

previousRandomState = rng;
restoreRandomState = onCleanup(@() rng(previousRandomState)); %#ok<NASGU>
rng(random_seed, 'twister');
outcomeDraws = rand(maximum_tests, 1);
measurementOffsets = usable_step_mm * 0.04 * randn(maximum_tests, 1);

answers = struct('study_mode', 'First study - variation unknown', ...
    'low_guess', '1', 'high_guess', '9', 'variation_guess', '', ...
    'maximum_tests', sprintf('%d', maximum_tests), ...
    'minimum_gap', '0', 'maximum_gap', '10', 'unit', 'mm', ...
    'physical_mode', 'Regular gap step', ...
    'regular_step', sprintf('%.2f', usable_step_mm), ...
    'confirmed_gaps', '', 'foil_thickness', '0.015');
parsed = parse_run_inputs(answers);
tolerance = parsed.cfg.reachable_model.comparison_tolerance_mm;
result = [];
record = [];
evalc('[result, record] = run_physical_test(parsed.params, maximum_tests, @synthetic_response, parsed.cfg);');

requested = record.requested_levels(:);
reachable = parsed.cfg.reachable_model.gaps_mm(:);
distanceToReachable = arrayfun(@(gap) min(abs(reachable - gap)), requested);
hasFit = isfield(result, 'has_overlap') && result.has_overlap && ...
    isfield(result, 'mu') && isfinite(result.mu) && ...
    isfield(result, 'sigma') && isfinite(result.sigma);

summary = struct( ...
    'true_middle_mm', true_middle_mm, ...
    'true_variation_mm', true_variation_mm, ...
    'usable_step_mm', usable_step_mm, ...
    'maximum_tests', maximum_tests, ...
    'random_seed', random_seed, ...
    'tests_requested', numel(requested), ...
    'search_scale_mm', parsed.params.spread_guess, ...
    'search_scale_source', parsed.cfg.search_scale_source, ...
    'all_requests_reachable', all(distanceToReachable <= tolerance), ...
    'all_requests_in_bounds', all(requested >= -tolerance & ...
        requested <= 10 + tolerance), ...
    'no_immediate_duplicate', numel(requested) < 2 || ...
        all(abs(diff(requested)) > tolerance), ...
    'has_overlap', result.has_overlap, ...
    'estimated_middle_mm', value_or_nan(result, 'mu', hasFit), ...
    'estimated_variation_mm', value_or_nan(result, 'sigma', hasFit), ...
    'middle_lower_mm', value_or_nan(result, 'mu_lo', hasFit), ...
    'middle_upper_mm', value_or_nan(result, 'mu_hi', hasFit), ...
    'variation_lower_mm', value_or_nan(result, 'sigma_lo', hasFit), ...
    'variation_upper_mm', value_or_nan(result, 'sigma_hi', hasFit), ...
    'middle_interval_contains_truth', interval_contains(result, ...
        'mu_lo', 'mu_hi', true_middle_mm, hasFit), ...
    'variation_interval_contains_truth', interval_contains(result, ...
        'sigma_lo', 'sigma_hi', true_variation_mm, hasFit), ...
    'status', char(string(record.status)));

    function response = synthetic_response(requestedGap, testNumber)
        measuredGap = min(10, max(0, ...
            requestedGap + measurementOffsets(testNumber)));
        if requestedGap <= tolerance
            outcome = true;
        elseif requestedGap >= 10 - tolerance
            outcome = false;
        else
            probability = shape_model(measuredGap, true_middle_mm, ...
                true_variation_mm).p;
            outcome = outcomeDraws(testNumber) <= probability;
        end
        response = struct('outcome', logical(outcome), ...
            'measurements', measuredGap);
    end
end

function yes = interval_contains(result, lowerField, upperField, truth, hasFit)
yes = hasFit && isfield(result, lowerField) && isfield(result, upperField) && ...
    isfinite(result.(lowerField)) && isfinite(result.(upperField)) && ...
    result.(lowerField) <= truth && truth <= result.(upperField);
end

function value = value_or_nan(result, fieldName, hasFit)
if hasFit && isfield(result, fieldName)
    value = result.(fieldName);
else
    value = NaN;
end
end
